<?php
/* 
** # DO NOT EDIT THIS FILE!  
** # Auto generated from: 
** # D:\doc\04.HMI协议（LARK）
** # 2024/6/5 10:20:45 
**/





/************基础参数配置************/
/* @brief 通道表尺寸，默认：4096
 * @param data1(4byte)-  @default [4096]
 */
define('REG_BNOISE_LUT_SIZE',                    1 ); /*R*/

/* @brief 指定底噪采样通道,
 *  0-ADC0_DDC0, 1-ADC0_DDC1
 *  2-ADC1_DDC0, 3-ADC1_DDC1
 *  4-ADC2_DDC0, 5-ADC2_DDC1
 *  6-ADC3_DDC0, 7-ADC3_DDC1
 * @param data1(4byte)-  @default [0]
 */
define('REG_SAMPLE_CHANNEL',                     2 ); /*RW*/

/* @brief 底噪采样次数，默认取20次
 * @param data1(4byte)-  @default [20]
 */
define('REG_SAMPLE_TIMES',                       3 ); /*RW*/

/* @brief 1启动/0停止底噪采样
 * @param data1(4byte)-  @default [0]
 */
define('REG_SAMPLE_ENABLE',                      4 ); /*RW*/

/* @brief 通过REG_DUMP读取指定通道的噪声实时数据（只读）
 * @param data1(4byte)-通道号  @default [0]
 */
define('REG_SAMPLE_DATA',                        5 ); /*R*/

/* @brief 自动采集循环
 * @param data1(4byte)-  @default [0]
 */
define('REG_SAMPLE_AUTO_TRAVERSAL',              6 ); /*RW*/



/************底噪计算************/
/* @brief 
 * @param data1(4byte)-  @default []
 */
define('REG_BNOISE_CACU',                        1024 ); /**/

/* @brief 
 * @param data1(4byte)-  @default []
 */
define('REG_BNOISE_BIN_DDC0',                    1025 ); /**/

/* @brief 
 * @param data1(4byte)-  @default []
 */
define('REG_BNOISE_BIN_DDC1',                    1026 ); /**/

/* @brief 
 * @param data1(4byte)-  @default []
 */
define('REG_BNOISE_MHZ_GAIN',                    1027 ); /**/












/************噪底查找表基地址************/
/* @brief ADC0-DDC0噪底查找表首值，总长度4096
 * @param data1(4byte)-  @default [0]
 */
define('REG_BNOISE_ADC0_DDC0_V0',               4096); /*RW*/

/* @brief ADC0-DDC1噪底查找表首值，总长度4096
 * @param data1(4byte)-  @default [0]
 */
define('REG_BNOISE_ADC0_DDC1_V0',                8192 ); /*RW*/

/* @brief ADC1-DDC0噪底查找表首值，总长度4096
 * @param data1(4byte)-  @default [0]
 */
define('REG_BNOISE_ADC1_DDC0_V0',                12288 ); /*RW*/

/* @brief ADC1-DDC1噪底查找表首值，总长度4096
 * @param data1(4byte)-  @default [0]
 */
define('REG_BNOISE_ADC1_DDC1_V0',                16384 ); /*RW*/

/* @brief ADC2-DDC0噪底查找表首值，总长度4096
 * @param data1(4byte)-  @default [0]
 */
define('REG_BNOISE_ADC2_DDC0_V0',                20480 ); /*RW*/

/* @brief ADC2-DDC1噪底查找表首值，总长度4096
 * @param data1(4byte)-  @default [0]
 */
define('REG_BNOISE_ADC2_DDC1_V0',                24576 ); /*RW*/

/* @brief ADC3-DDC0噪底查找表首值，总长度4096
 * @param data1(4byte)-  @default [0]
 */
define('REG_BNOISE_ADC3_DDC0_V0',                28672 ); /*RW*/

/* @brief ADC3-DDC1噪底查找表首值，总长度4096
 * @param data1(4byte)-  @default [0]
 */
define('REG_BNOISE_ADC3_DDC1_V0',                32768 ); /*RW*/

/* @brief ADC4-DDC0噪底查找表首值，总长度4096
 * @param data1(4byte)-  @default [0]
 */
define('REG_BNOISE_ADC4_DDC0_V0',                36864 ); /*RW*/

/* @brief ADC4-DDC1噪底查找表首值，总长度4096
 * @param data1(4byte)-  @default [0]
 */
define('REG_BNOISE_ADC4_DDC1_V0',                40960 ); /*RW*/

/* @brief ADC5-DDC0噪底查找表首值，总长度4096
 * @param data1(4byte)-  @default [0]
 */
define('REG_BNOISE_ADC5_DDC0_V0',                45056 ); /*RW*/

/* @brief ADC5-DDC1噪底查找表首值，总长度4096
 * @param data1(4byte)-  @default [0]
 */
define('REG_BNOISE_ADC5_DDC1_V0',                49152 ); /*RW*/

/* @brief ADC6-DDC0噪底查找表首值，总长度4096
 * @param data1(4byte)-  @default [0]
 */
define('REG_BNOISE_ADC6_DDC0_V0',                53248 ); /*RW*/

/* @brief ADC6-DDC1噪底查找表首值，总长度4096
 * @param data1(4byte)-  @default [0]
 */
define('REG_BNOISE_ADC6_DDC1_V0',                57344 ); /*RW*/

/* @brief ADC7-DDC0噪底查找表首值，总长度4096
 * @param data1(4byte)-  @default [0]
 */
define('REG_BNOISE_ADC7_DDC0_V0',                61440 ); /*RW*/

/* @brief ADC7-DDC1噪底查找表首值，总长度4096
 * @param data1(4byte)-  @default [0]
 */
define('REG_BNOISE_ADC7_DDC1_V0',                65536 ); /*RW*/


/* @brief 最大范围
 * @param data1(4byte)-  @default [0]
 */
define('REG_BNOISE_LAST',                        69632 ); /*R*/


/* 寄存器总数量 */
define('BNOISE_REG_CNT',         4097 );




