<?php
/* 
** # DO NOT EDIT THIS FILE!  
** # Auto generated from: 
** # D:\t\13.FML\00.doc\03.HMI协议
** # 2023/7/7 11:09:28 
**/






/* @brief 通道0使能/纵向角/横向角补偿/通道重映射 */
define('REG_CH_ENABLE_0',                        0 ); /*RW @default [1*/
define('REG_CH_ELEVATION_0',                     0 ); /*RW @default [12870*/
define('REG_CH_AZIMUTH_OFF_0',                   0 ); /*RW @default [0*/
define('REG_CH_REMAP_0',                         0 ); /*RW @default [33*/

/* @brief 通道1使能/纵向角/横向角补偿/通道重映射 */
define('REG_CH_ENABLE_1',                        1 ); /*RW @default [1*/
define('REG_CH_ELEVATION_1',                     1 ); /*RW @default [9990*/
define('REG_CH_AZIMUTH_OFF_1',                   1 ); /*RW @default [0*/
define('REG_CH_REMAP_1',                         1 ); /*RW @default [35*/

/* @brief 通道2使能/纵向角/横向角补偿/通道重映射 */
define('REG_CH_ENABLE_2',                        2 ); /*RW @default [1*/
define('REG_CH_ELEVATION_2',                     2 ); /*RW @default [7060*/
define('REG_CH_AZIMUTH_OFF_2',                   2 ); /*RW @default [0*/
define('REG_CH_REMAP_2',                         2 ); /*RW @default [37*/

/* @brief 通道3使能/纵向角/横向角补偿/通道重映射 */
define('REG_CH_ENABLE_3',                        3 ); /*RW @default [1*/
define('REG_CH_ELEVATION_3',                     3 ); /*RW @default [5080*/
define('REG_CH_AZIMUTH_OFF_3',                   3 ); /*RW @default [0*/
define('REG_CH_REMAP_3',                         3 ); /*RW @default [39*/

/* @brief 通道4使能/纵向角/横向角补偿/通道重映射 */
define('REG_CH_ENABLE_4',                        4 ); /*RW @default [1*/
define('REG_CH_ELEVATION_4',                     4 ); /*RW @default [4090*/
define('REG_CH_AZIMUTH_OFF_4',                   4 ); /*RW @default [0*/
define('REG_CH_REMAP_4',                         4 ); /*RW @default [17*/

/* @brief 通道5使能/纵向角/横向角补偿/通道重映射 */
define('REG_CH_ENABLE_5',                        5 ); /*RW @default [1*/
define('REG_CH_ELEVATION_5',                     5 ); /*RW @default [3920*/
define('REG_CH_AZIMUTH_OFF_5',                   5 ); /*RW @default [0*/
define('REG_CH_REMAP_5',                         5 ); /*RW @default [19*/

/* @brief 通道6使能/纵向角/横向角补偿/通道重映射 */
define('REG_CH_ENABLE_6',                        6 ); /*RW @default [1*/
define('REG_CH_ELEVATION_6',                     6 ); /*RW @default [3750*/
define('REG_CH_AZIMUTH_OFF_6',                   6 ); /*RW @default [0*/
define('REG_CH_REMAP_6',                         6 ); /*RW @default [21*/

/* @brief 通道7使能/纵向角/横向角补偿/通道重映射 */
define('REG_CH_ENABLE_7',                        7 ); /*RW @default [1*/
define('REG_CH_ELEVATION_7',                     7 ); /*RW @default [3590*/
define('REG_CH_AZIMUTH_OFF_7',                   7 ); /*RW @default [0*/
define('REG_CH_REMAP_7',                         7 ); /*RW @default [23*/

/* @brief 通道8使能/纵向角/横向角补偿/通道重映射 */
define('REG_CH_ENABLE_8',                        8 ); /*RW @default [1*/
define('REG_CH_ELEVATION_8',                     8 ); /*RW @default [3420*/
define('REG_CH_AZIMUTH_OFF_8',                   8 ); /*RW @default [0*/
define('REG_CH_REMAP_8',                         8 ); /*RW @default [1*/

/* @brief 通道9使能/纵向角/横向角补偿/通道重映射 */
define('REG_CH_ENABLE_9',                        9 ); /*RW @default [1*/
define('REG_CH_ELEVATION_9',                     9 ); /*RW @default [3250*/
define('REG_CH_AZIMUTH_OFF_9',                   9 ); /*RW @default [0*/
define('REG_CH_REMAP_9',                         9 ); /*RW @default [3*/

/* @brief 通道10使能/纵向角/横向角补偿/通道重映射 */
define('REG_CH_ENABLE_10',                       10 ); /*RW @default [1*/
define('REG_CH_ELEVATION_10',                    10 ); /*RW @default [3090*/
define('REG_CH_AZIMUTH_OFF_10',                  10 ); /*RW @default [0*/
define('REG_CH_REMAP_10',                        10 ); /*RW @default [5*/

/* @brief 通道11使能/纵向角/横向角补偿/通道重映射 */
define('REG_CH_ENABLE_11',                       11 ); /*RW @default [1*/
define('REG_CH_ELEVATION_11',                    11 ); /*RW @default [2920*/
define('REG_CH_AZIMUTH_OFF_11',                  11 ); /*RW @default [0*/
define('REG_CH_REMAP_11',                        11 ); /*RW @default [7*/

/* @brief 通道12使能/纵向角/横向角补偿/通道重映射 */
define('REG_CH_ENABLE_12',                       12 ); /*RW @default [1*/
define('REG_CH_ELEVATION_12',                    12 ); /*RW @default [2750*/
define('REG_CH_AZIMUTH_OFF_12',                  12 ); /*RW @default [0*/
define('REG_CH_REMAP_12',                        12 ); /*RW @default [49*/

/* @brief 通道13使能/纵向角/横向角补偿/通道重映射 */
define('REG_CH_ENABLE_13',                       13 ); /*RW @default [1*/
define('REG_CH_ELEVATION_13',                    13 ); /*RW @default [2590*/
define('REG_CH_AZIMUTH_OFF_13',                  13 ); /*RW @default [0*/
define('REG_CH_REMAP_13',                        13 ); /*RW @default [51*/

/* @brief 通道14使能/纵向角/横向角补偿/通道重映射 */
define('REG_CH_ENABLE_14',                       14 ); /*RW @default [1*/
define('REG_CH_ELEVATION_14',                    14 ); /*RW @default [2420*/
define('REG_CH_AZIMUTH_OFF_14',                  14 ); /*RW @default [0*/
define('REG_CH_REMAP_14',                        14 ); /*RW @default [53*/

/* @brief 通道15使能/纵向角/横向角补偿/通道重映射 */
define('REG_CH_ENABLE_15',                       15 ); /*RW @default [1*/
define('REG_CH_ELEVATION_15',                    15 ); /*RW @default [2250*/
define('REG_CH_AZIMUTH_OFF_15',                  15 ); /*RW @default [0*/
define('REG_CH_REMAP_15',                        15 ); /*RW @default [55*/

/* @brief 通道16使能/纵向角/横向角补偿/通道重映射 */
define('REG_CH_ENABLE_16',                       16 ); /*RW @default [1*/
define('REG_CH_ELEVATION_16',                    16 ); /*RW @default [2090*/
define('REG_CH_AZIMUTH_OFF_16',                  16 ); /*RW @default [0*/
define('REG_CH_REMAP_16',                        16 ); /*RW @default [41*/

/* @brief 通道17使能/纵向角/横向角补偿/通道重映射 */
define('REG_CH_ENABLE_17',                       17 ); /*RW @default [1*/
define('REG_CH_ELEVATION_17',                    17 ); /*RW @default [1920*/
define('REG_CH_AZIMUTH_OFF_17',                  17 ); /*RW @default [0*/
define('REG_CH_REMAP_17',                        17 ); /*RW @default [43*/

/* @brief 通道18使能/纵向角/横向角补偿/通道重映射 */
define('REG_CH_ENABLE_18',                       18 ); /*RW @default [1*/
define('REG_CH_ELEVATION_18',                    18 ); /*RW @default [1750*/
define('REG_CH_AZIMUTH_OFF_18',                  18 ); /*RW @default [0*/
define('REG_CH_REMAP_18',                        18 ); /*RW @default [45*/

/* @brief 通道19使能/纵向角/横向角补偿/通道重映射 */
define('REG_CH_ENABLE_19',                       19 ); /*RW @default [1*/
define('REG_CH_ELEVATION_19',                    19 ); /*RW @default [1590*/
define('REG_CH_AZIMUTH_OFF_19',                  19 ); /*RW @default [0*/
define('REG_CH_REMAP_19',                        19 ); /*RW @default [47*/

/* @brief 通道20使能/纵向角/横向角补偿/通道重映射 */
define('REG_CH_ENABLE_20',                       20 ); /*RW @default [1*/
define('REG_CH_ELEVATION_20',                    20 ); /*RW @default [1420*/
define('REG_CH_AZIMUTH_OFF_20',                  20 ); /*RW @default [0*/
define('REG_CH_REMAP_20',                        20 ); /*RW @default [25*/

/* @brief 通道21使能/纵向角/横向角补偿/通道重映射 */
define('REG_CH_ENABLE_21',                       21 ); /*RW @default [1*/
define('REG_CH_ELEVATION_21',                    21 ); /*RW @default [1250*/
define('REG_CH_AZIMUTH_OFF_21',                  21 ); /*RW @default [0*/
define('REG_CH_REMAP_21',                        21 ); /*RW @default [27*/

/* @brief 通道22使能/纵向角/横向角补偿/通道重映射 */
define('REG_CH_ENABLE_22',                       22 ); /*RW @default [1*/
define('REG_CH_ELEVATION_22',                    22 ); /*RW @default [1090*/
define('REG_CH_AZIMUTH_OFF_22',                  22 ); /*RW @default [0*/
define('REG_CH_REMAP_22',                        22 ); /*RW @default [29*/

/* @brief 通道23使能/纵向角/横向角补偿/通道重映射 */
define('REG_CH_ENABLE_23',                       23 ); /*RW @default [1*/
define('REG_CH_ELEVATION_23',                    23 ); /*RW @default [920*/
define('REG_CH_AZIMUTH_OFF_23',                  23 ); /*RW @default [0*/
define('REG_CH_REMAP_23',                        23 ); /*RW @default [31*/

/* @brief 通道24使能/纵向角/横向角补偿/通道重映射 */
define('REG_CH_ENABLE_24',                       24 ); /*RW @default [1*/
define('REG_CH_ELEVATION_24',                    24 ); /*RW @default [750*/
define('REG_CH_AZIMUTH_OFF_24',                  24 ); /*RW @default [0*/
define('REG_CH_REMAP_24',                        24 ); /*RW @default [9*/

/* @brief 通道25使能/纵向角/横向角补偿/通道重映射 */
define('REG_CH_ENABLE_25',                       25 ); /*RW @default [1*/
define('REG_CH_ELEVATION_25',                    25 ); /*RW @default [590*/
define('REG_CH_AZIMUTH_OFF_25',                  25 ); /*RW @default [0*/
define('REG_CH_REMAP_25',                        25 ); /*RW @default [11*/

/* @brief 通道26使能/纵向角/横向角补偿/通道重映射 */
define('REG_CH_ENABLE_26',                       26 ); /*RW @default [1*/
define('REG_CH_ELEVATION_26',                    26 ); /*RW @default [420*/
define('REG_CH_AZIMUTH_OFF_26',                  26 ); /*RW @default [0*/
define('REG_CH_REMAP_26',                        26 ); /*RW @default [13*/

/* @brief 通道27使能/纵向角/横向角补偿/通道重映射 */
define('REG_CH_ENABLE_27',                       27 ); /*RW @default [1*/
define('REG_CH_ELEVATION_27',                    27 ); /*RW @default [250*/
define('REG_CH_AZIMUTH_OFF_27',                  27 ); /*RW @default [0*/
define('REG_CH_REMAP_27',                        27 ); /*RW @default [15*/

/* @brief 通道28使能/纵向角/横向角补偿/通道重映射 */
define('REG_CH_ENABLE_28',                       28 ); /*RW @default [1*/
define('REG_CH_ELEVATION_28',                    28 ); /*RW @default [80*/
define('REG_CH_AZIMUTH_OFF_28',                  28 ); /*RW @default [0*/
define('REG_CH_REMAP_28',                        28 ); /*RW @default [57*/

/* @brief 通道29使能/纵向角/横向角补偿/通道重映射 */
define('REG_CH_ENABLE_29',                       29 ); /*RW @default [1*/
define('REG_CH_ELEVATION_29',                    29 ); /*RW @default [-80*/
define('REG_CH_AZIMUTH_OFF_29',                  29 ); /*RW @default [0*/
define('REG_CH_REMAP_29',                        29 ); /*RW @default [59*/

/* @brief 通道30使能/纵向角/横向角补偿/通道重映射 */
define('REG_CH_ENABLE_30',                       30 ); /*RW @default [1*/
define('REG_CH_ELEVATION_30',                    30 ); /*RW @default [-250*/
define('REG_CH_AZIMUTH_OFF_30',                  30 ); /*RW @default [0*/
define('REG_CH_REMAP_30',                        30 ); /*RW @default [61*/

/* @brief 通道31使能/纵向角/横向角补偿/通道重映射 */
define('REG_CH_ENABLE_31',                       31 ); /*RW @default [1*/
define('REG_CH_ELEVATION_31',                    31 ); /*RW @default [-420*/
define('REG_CH_AZIMUTH_OFF_31',                  31 ); /*RW @default [0*/
define('REG_CH_REMAP_31',                        31 ); /*RW @default [63*/

/* @brief 通道32使能/纵向角/横向角补偿/通道重映射 */
define('REG_CH_ENABLE_32',                       32 ); /*RW @default [1*/
define('REG_CH_ELEVATION_32',                    32 ); /*RW @default [-580*/
define('REG_CH_AZIMUTH_OFF_32',                  32 ); /*RW @default [0*/
define('REG_CH_REMAP_32',                        32 ); /*RW @default [34*/

/* @brief 通道33使能/纵向角/横向角补偿/通道重映射 */
define('REG_CH_ENABLE_33',                       33 ); /*RW @default [1*/
define('REG_CH_ELEVATION_33',                    33 ); /*RW @default [-750*/
define('REG_CH_AZIMUTH_OFF_33',                  33 ); /*RW @default [0*/
define('REG_CH_REMAP_33',                        33 ); /*RW @default [36*/

/* @brief 通道34使能/纵向角/横向角补偿/通道重映射 */
define('REG_CH_ENABLE_34',                       34 ); /*RW @default [1*/
define('REG_CH_ELEVATION_34',                    34 ); /*RW @default [-920*/
define('REG_CH_AZIMUTH_OFF_34',                  34 ); /*RW @default [0*/
define('REG_CH_REMAP_34',                        34 ); /*RW @default [38*/

/* @brief 通道35使能/纵向角/横向角补偿/通道重映射 */
define('REG_CH_ENABLE_35',                       35 ); /*RW @default [1*/
define('REG_CH_ELEVATION_35',                    35 ); /*RW @default [-1080*/
define('REG_CH_AZIMUTH_OFF_35',                  35 ); /*RW @default [0*/
define('REG_CH_REMAP_35',                        35 ); /*RW @default [40*/

/* @brief 通道36使能/纵向角/横向角补偿/通道重映射 */
define('REG_CH_ENABLE_36',                       36 ); /*RW @default [1*/
define('REG_CH_ELEVATION_36',                    36 ); /*RW @default [-1250*/
define('REG_CH_AZIMUTH_OFF_36',                  36 ); /*RW @default [0*/
define('REG_CH_REMAP_36',                        36 ); /*RW @default [18*/

/* @brief 通道37使能/纵向角/横向角补偿/通道重映射 */
define('REG_CH_ENABLE_37',                       37 ); /*RW @default [1*/
define('REG_CH_ELEVATION_37',                    37 ); /*RW @default [-1420*/
define('REG_CH_AZIMUTH_OFF_37',                  37 ); /*RW @default [0*/
define('REG_CH_REMAP_37',                        37 ); /*RW @default [20*/

/* @brief 通道38使能/纵向角/横向角补偿/通道重映射 */
define('REG_CH_ENABLE_38',                       38 ); /*RW @default [1*/
define('REG_CH_ELEVATION_38',                    38 ); /*RW @default [-1590*/
define('REG_CH_AZIMUTH_OFF_38',                  38 ); /*RW @default [0*/
define('REG_CH_REMAP_38',                        38 ); /*RW @default [22*/

/* @brief 通道39使能/纵向角/横向角补偿/通道重映射 */
define('REG_CH_ENABLE_39',                       39 ); /*RW @default [1*/
define('REG_CH_ELEVATION_39',                    39 ); /*RW @default [-1750*/
define('REG_CH_AZIMUTH_OFF_39',                  39 ); /*RW @default [0*/
define('REG_CH_REMAP_39',                        39 ); /*RW @default [24*/

/* @brief 通道40使能/纵向角/横向角补偿/通道重映射 */
define('REG_CH_ENABLE_40',                       40 ); /*RW @default [1*/
define('REG_CH_ELEVATION_40',                    40 ); /*RW @default [-1920*/
define('REG_CH_AZIMUTH_OFF_40',                  40 ); /*RW @default [0*/
define('REG_CH_REMAP_40',                        40 ); /*RW @default [2*/

/* @brief 通道41使能/纵向角/横向角补偿/通道重映射 */
define('REG_CH_ENABLE_41',                       41 ); /*RW @default [1*/
define('REG_CH_ELEVATION_41',                    41 ); /*RW @default [-2090*/
define('REG_CH_AZIMUTH_OFF_41',                  41 ); /*RW @default [0*/
define('REG_CH_REMAP_41',                        41 ); /*RW @default [4*/

/* @brief 通道42使能/纵向角/横向角补偿/通道重映射 */
define('REG_CH_ENABLE_42',                       42 ); /*RW @default [1*/
define('REG_CH_ELEVATION_42',                    42 ); /*RW @default [-2250*/
define('REG_CH_AZIMUTH_OFF_42',                  42 ); /*RW @default [0*/
define('REG_CH_REMAP_42',                        42 ); /*RW @default [6*/

/* @brief 通道43使能/纵向角/横向角补偿/通道重映射 */
define('REG_CH_ENABLE_43',                       43 ); /*RW @default [1*/
define('REG_CH_ELEVATION_43',                    43 ); /*RW @default [-2420*/
define('REG_CH_AZIMUTH_OFF_43',                  43 ); /*RW @default [0*/
define('REG_CH_REMAP_43',                        43 ); /*RW @default [8*/

/* @brief 通道44使能/纵向角/横向角补偿/通道重映射 */
define('REG_CH_ENABLE_44',                       44 ); /*RW @default [1*/
define('REG_CH_ELEVATION_44',                    44 ); /*RW @default [-2590*/
define('REG_CH_AZIMUTH_OFF_44',                  44 ); /*RW @default [0*/
define('REG_CH_REMAP_44',                        44 ); /*RW @default [50*/

/* @brief 通道45使能/纵向角/横向角补偿/通道重映射 */
define('REG_CH_ENABLE_45',                       45 ); /*RW @default [1*/
define('REG_CH_ELEVATION_45',                    45 ); /*RW @default [-2750*/
define('REG_CH_AZIMUTH_OFF_45',                  45 ); /*RW @default [0*/
define('REG_CH_REMAP_45',                        45 ); /*RW @default [52*/

/* @brief 通道46使能/纵向角/横向角补偿/通道重映射 */
define('REG_CH_ENABLE_46',                       46 ); /*RW @default [1*/
define('REG_CH_ELEVATION_46',                    46 ); /*RW @default [-2920*/
define('REG_CH_AZIMUTH_OFF_46',                  46 ); /*RW @default [0*/
define('REG_CH_REMAP_46',                        46 ); /*RW @default [54*/

/* @brief 通道47使能/纵向角/横向角补偿/通道重映射 */
define('REG_CH_ENABLE_47',                       47 ); /*RW @default [1*/
define('REG_CH_ELEVATION_47',                    47 ); /*RW @default [-3090*/
define('REG_CH_AZIMUTH_OFF_47',                  47 ); /*RW @default [0*/
define('REG_CH_REMAP_47',                        47 ); /*RW @default [56*/

/* @brief 通道48使能/纵向角/横向角补偿/通道重映射 */
define('REG_CH_ENABLE_48',                       48 ); /*RW @default [1*/
define('REG_CH_ELEVATION_48',                    48 ); /*RW @default [-3250*/
define('REG_CH_AZIMUTH_OFF_48',                  48 ); /*RW @default [0*/
define('REG_CH_REMAP_48',                        48 ); /*RW @default [42*/

/* @brief 通道49使能/纵向角/横向角补偿/通道重映射 */
define('REG_CH_ENABLE_49',                       49 ); /*RW @default [1*/
define('REG_CH_ELEVATION_49',                    49 ); /*RW @default [-3420*/
define('REG_CH_AZIMUTH_OFF_49',                  49 ); /*RW @default [0*/
define('REG_CH_REMAP_49',                        49 ); /*RW @default [44*/

/* @brief 通道50使能/纵向角/横向角补偿/通道重映射 */
define('REG_CH_ENABLE_50',                       50 ); /*RW @default [1*/
define('REG_CH_ELEVATION_50',                    50 ); /*RW @default [-3590*/
define('REG_CH_AZIMUTH_OFF_50',                  50 ); /*RW @default [0*/
define('REG_CH_REMAP_50',                        50 ); /*RW @default [46*/

/* @brief 通道51使能/纵向角/横向角补偿/通道重映射 */
define('REG_CH_ENABLE_51',                       51 ); /*RW @default [1*/
define('REG_CH_ELEVATION_51',                    51 ); /*RW @default [-3750*/
define('REG_CH_AZIMUTH_OFF_51',                  51 ); /*RW @default [0*/
define('REG_CH_REMAP_51',                        51 ); /*RW @default [48*/

/* @brief 通道52使能/纵向角/横向角补偿/通道重映射 */
define('REG_CH_ENABLE_52',                       52 ); /*RW @default [1*/
define('REG_CH_ELEVATION_52',                    52 ); /*RW @default [-3920*/
define('REG_CH_AZIMUTH_OFF_52',                  52 ); /*RW @default [0*/
define('REG_CH_REMAP_52',                        52 ); /*RW @default [26*/

/* @brief 通道53使能/纵向角/横向角补偿/通道重映射 */
define('REG_CH_ENABLE_53',                       53 ); /*RW @default [1*/
define('REG_CH_ELEVATION_53',                    53 ); /*RW @default [-4080*/
define('REG_CH_AZIMUTH_OFF_53',                  53 ); /*RW @default [0*/
define('REG_CH_REMAP_53',                        53 ); /*RW @default [28*/

/* @brief 通道54使能/纵向角/横向角补偿/通道重映射 */
define('REG_CH_ENABLE_54',                       54 ); /*RW @default [1*/
define('REG_CH_ELEVATION_54',                    54 ); /*RW @default [-4880*/
define('REG_CH_AZIMUTH_OFF_54',                  54 ); /*RW @default [0*/
define('REG_CH_REMAP_54',                        54 ); /*RW @default [30*/

/* @brief 通道55使能/纵向角/横向角补偿/通道重映射 */
define('REG_CH_ENABLE_55',                       55 ); /*RW @default [1*/
define('REG_CH_ELEVATION_55',                    55 ); /*RW @default [-5670*/
define('REG_CH_AZIMUTH_OFF_55',                  55 ); /*RW @default [0*/
define('REG_CH_REMAP_55',                        55 ); /*RW @default [32*/

/* @brief 通道56使能/纵向角/横向角补偿/通道重映射 */
define('REG_CH_ENABLE_56',                       56 ); /*RW @default [1*/
define('REG_CH_ELEVATION_56',                    56 ); /*RW @default [-6460*/
define('REG_CH_AZIMUTH_OFF_56',                  56 ); /*RW @default [0*/
define('REG_CH_REMAP_56',                        56 ); /*RW @default [10*/

/* @brief 通道57使能/纵向角/横向角补偿/通道重映射 */
define('REG_CH_ENABLE_57',                       57 ); /*RW @default [1*/
define('REG_CH_ELEVATION_57',                    57 ); /*RW @default [-7250*/
define('REG_CH_AZIMUTH_OFF_57',                  57 ); /*RW @default [0*/
define('REG_CH_REMAP_57',                        57 ); /*RW @default [12*/

/* @brief 通道58使能/纵向角/横向角补偿/通道重映射 */
define('REG_CH_ENABLE_58',                       58 ); /*RW @default [1*/
define('REG_CH_ELEVATION_58',                    58 ); /*RW @default [-8040*/
define('REG_CH_AZIMUTH_OFF_58',                  58 ); /*RW @default [0*/
define('REG_CH_REMAP_58',                        58 ); /*RW @default [14*/

/* @brief 通道59使能/纵向角/横向角补偿/通道重映射 */
define('REG_CH_ENABLE_59',                       59 ); /*RW @default [1*/
define('REG_CH_ELEVATION_59',                    59 ); /*RW @default [-8820*/
define('REG_CH_AZIMUTH_OFF_59',                  59 ); /*RW @default [0*/
define('REG_CH_REMAP_59',                        59 ); /*RW @default [16*/

/* @brief 通道60使能/纵向角/横向角补偿/通道重映射 */
define('REG_CH_ENABLE_60',                       60 ); /*RW @default [1*/
define('REG_CH_ELEVATION_60',                    60 ); /*RW @default [-9600*/
define('REG_CH_AZIMUTH_OFF_60',                  60 ); /*RW @default [0*/
define('REG_CH_REMAP_60',                        60 ); /*RW @default [58*/

/* @brief 通道61使能/纵向角/横向角补偿/通道重映射 */
define('REG_CH_ENABLE_61',                       61 ); /*RW @default [1*/
define('REG_CH_ELEVATION_61',                    61 ); /*RW @default [-10380*/
define('REG_CH_AZIMUTH_OFF_61',                  61 ); /*RW @default [0*/
define('REG_CH_REMAP_61',                        61 ); /*RW @default [60*/

/* @brief 通道62使能/纵向角/横向角补偿/通道重映射 */
define('REG_CH_ENABLE_62',                       62 ); /*RW @default [1*/
define('REG_CH_ELEVATION_62',                    62 ); /*RW @default [-11150*/
define('REG_CH_AZIMUTH_OFF_62',                  62 ); /*RW @default [0*/
define('REG_CH_REMAP_62',                        62 ); /*RW @default [62*/

/* @brief 通道63使能/纵向角/横向角补偿/通道重映射 */
define('REG_CH_ENABLE_63',                       63 ); /*RW @default [1*/
define('REG_CH_ELEVATION_63',                    63 ); /*RW @default [-11920*/
define('REG_CH_AZIMUTH_OFF_63',                  63 ); /*RW @default [0*/
define('REG_CH_REMAP_63',                        63 ); /*RW @default [64*/


/* 寄存器总数量 */
define('CHANNELS_REG_CNT',       64 );




