<?php
/* 
** # DO NOT EDIT THIS FILE!  
** # Auto generated from: 
** # D:\t\11.FM1\00.doc\03.协议
** # 2023/7/6 10:50:44 
**/





/************基础参数************/
/* @brief 基础控制点：
 *  1.原点回归 %MW20.0
 *  2.停止 %MW20.1
 *  3.启动 %MW20.2
 *  4.jog正转 %MW20.3
 *  5.jog反转 %MW20.4
 *  6.计数器复位 %MW20.6
 * @param data1(4byte)-  @default [0]
 */
define('REG_BASE_CTRL',                          1 ); /*RW*/

/* @brief 运动模式 %MW22
 *  0：单次运动，需要撞原点
 *  1：往复运动，需要撞原点
 *  2：绝对运动，无需撞原点
 * @param data1(4byte)-  @default [0]
 */
define('REG_BID_MOTION',                         2 ); /*RW*/

/* @brief 目标位移设置 %MW100
 * @param data1(4byte)-  @default [0]
 */
define('REG_TARGET_POS',                         3 ); /*RW*/

/* @brief 目标速度设置 %MW106
 * @param data1(4byte)-  @default [0]
 */
define('REG_TARGET_SPEED',                       4 ); /*RW*/

/* @brief 运动加速度（脉冲数） %MW122
 *  范围：[5000,20000]
 * @param data1(4byte)-  @default [10000]
 */
define('REG_MOTION_ACCE',                        5 ); /*RW*/

/* @brief 运动减速度（脉冲数） %MW124
 *  范围：[5000,20000]
 * @param data1(4byte)-  @default [10000]
 */
define('REG_MOTION_DECE',                        6 ); /*RW*/

/* @brief 目标循环次数 %MW108
 * @param data1(4byte)-  @default [1]
 */
define('REG_TARGET_CYCLE',                       7 ); /*RW*/









/************状态信息************/
/* @brief PLC软件版本号
 * @param data1(4byte)-  @default [0]
 */
define('REG_PLC_VERSION',                        33 ); /*R*/

/* @brief 当前位移 %MW102，单位0.1mm
 * @param data1(4byte)-  @default [0]
 */
define('REG_X1_POS',                             34 ); /*R*/

/* @brief 当前速度 %MW104
 * @param data1(4byte)-  @default [0]
 */
define('REG_X1_SPEED',                           35 ); /*R*/

/* @brief 当前循环计数 %MW110
 * @param data1(4byte)-  @default [0]
 */
define('REG_X1_CYCLE',                           36 ); /*R*/

/* @brief X1当前扭矩 %MW112
 * @param data1(4byte)-  @default [0]
 */
define('REG_X1_ACT_TRQ',                         37 ); /*R*/

/* @brief X1状态 %MW116
 * @param data1(4byte)-  @default [0]
 */
define('REG_X1_ACT_STATE',                       38 ); /*R*/

/* @brief XI当前电流 %MW118
 * @param data1(4byte)-  @default [0]
 */
define('REG_X1_ACT_CURRENT',                     39 ); /*R*/

/* @brief X1当前脉冲数 %MW120
 * @param data1(4byte)-  @default [0]
 */
define('REG_X1_ACT_PULSE',                       40 ); /*R*/

/* @brief X2(SSI)当前值L(%MW136)，单位0.1mm
 * @param data1(4byte)-  @default [0]
 */
define('REG_X2_POS_L',                           41 ); /*R*/

/* @brief X2(SSI)当前值H(%MW137)，单位0.1mm
 * @param data1(4byte)-  @default [0]
 */
define('REG_X2_POS_H',                           42 ); /*R*/

/* @brief 缓存的AXIS1统计值-上层实现
 * @param data1(4byte)-  @default [0]
 */
define('REG_AXIS1_STA_VALUE',                    43 ); /*R*/

/* @brief 缓存的AXIS2统计值-上层实现
 * @param data1(4byte)-  @default [0]
 */
define('REG_AXIS2_STA_VALUE',                    44 ); /*R*/









/* 寄存器总数量 */
define('DELTA_REG_CNT',          45 );




