<?php
/* 
** # DO NOT EDIT THIS FILE!  
** # Auto generated from: 
** # D:\t\17.LARK\00.doc\03.HMI协议
** # 2024/5/16 14:06:20 
**/




/************通用错误************/
/* 正常
 */
define('ERR_OK',                                 0 ); /* hex:0x0*/

/* 一般错误
 */
define('ERR_NORMAL',                             1 ); /* hex:0x1*/

/* 内存不够，对象申请失败
 */
define('ERR_OUT_OF_MEMORY',                      2 ); /* hex:0x2*/

/* tcp_bind失败
 */
define('ERR_BIND_FAILED',                        3 ); /* hex:0x3*/

/* tcp listen失败，端口可能被占用
 */
define('ERR_LISTEN_FAILED',                      4 ); /* hex:0x4*/

/* 对象已存在
 */
define('ERR_OBJECT_EXISTED',                     5 ); /* hex:0x5*/

/* 对象不存在
 */
define('ERR_OBJECT_NOT_EXIST',                   6 ); /* hex:0x6*/

/* 句柄不合法
 */
define('ERR_INVALID_HANDLE',                     7 ); /* hex:0x7*/

/* 超时错误
 */
define('ERR_TIMEOUT',                            8 ); /* hex:0x8*/

/* 连接断开
 */
define('ERR_DISCONNECTED',                       9 ); /* hex:0x9*/

/* 参数不合法
 */
define('ERR_INVALID_PARA',                       10 ); /* hex:0xA*/

/* tcp发送失败
 */
define('ERR_SEND_FAILED',                        11 ); /* hex:0xB*/

/* 缓冲区满
 */
define('ERR_BUFFER_FULL',                        12 ); /* hex:0xC*/

/* 不合法的地址
 */
define('ERR_INVALID_REG_ADDR',                   13 ); /* hex:0xD*/

/* IAP升级中
 */
define('ERR_IAP_RUNNING',                        14 ); /* hex:0xE*/

/* 对象已打开
 */
define('ERR_ALREADY_OPEN',                       15 ); /* hex:0xF*/

/* 拒绝访问
 */
define('ERR_ACCESS_DENIED',                      16 ); /* hex:0x10*/

/* 总线未准备好
 */
define('ERR_BUS_NOT_READY',                      17 ); /* hex:0x11*/

/* 数据不完整
 */
define('ERR_DATA_INCOMPLETE',                    18 ); /* hex:0x12*/

/* 需要重传
 */
define('ERR_NEED_RESEND',                        19 ); /* hex:0x13*/

/* 校验错误
 */
define('ERR_CHECKSUM_ERROR',                     20 ); /* hex:0x14*/

/* tcp数据错误-header错乱
 */
define('ERR_TCP_DATA_ERROR',                     21 ); /* hex:0x15*/

/* 跳过处理
 */
define('ERR_SKIPPED',                            22 ); /* hex:0x16*/

/* 任务等待
 */
define('ERR_PENDING',                            23 ); /* hex:0x17*/

/* 任务忙
 */
define('ERR_BUSY',                               24 ); /* hex:0x18*/

/* 不合法的设备ID
 */
define('ERR_INVALID_DEV_ID',                     25 ); /* hex:0x19*/

/* 初始化失败
 */
define('ERR_INIT_FAILURE',                       26 ); /* hex:0x1A*/

/* 系统重新执行初始化（告警）
 */
define('ERR_SYSTEM_REINIT',                      27 ); /* hex:0x1B*/

/* 数据为空
 */
define('ERR_EMPTY',                              28 ); /* hex:0x1C*/

/* 遇到关键节点
 */
define('ERR_KEY_NODE',                           29 ); /* hex:0x1D*/

/* 版本不匹配
 */
define('ERR_VERSION_MISMATCH',                   30 ); /* hex:0x1E*/

/* TAG不匹配
 */
define('ERR_TAG_MIAMATCH',                       31 ); /* hex:0x1F*/

/* 页面不存在-404
 */
define('ERR_404',                                32 ); /* hex:0x20*/

/* 连接被踢掉
 */
define('ERR_CONN_DROPED',                        33 ); /* hex:0x21*/

/* UDP发送点云被禁止
 */
define('ERR_UDP_TRANS_DISABLED',                 34 ); /* hex:0x22*/

/* Host IP发生变化
 */
define('ERR_HOST_IP_CHANGED',                    35 ); /* hex:0x23*/

/* Device IP发生变化
 */
define('ERR_DEVICE_IP_CHANGED',                  36 ); /* hex:0x24*/

/* 不合法的IP
 */
define('ERR_INVALID_IP_ADDR',                    37 ); /* hex:0x25*/

/* 文件尾
 */
define('ERR_EOF',                                38 ); /* hex:0x26*/

/************BSP专用错误定义************/
/* xemac模块初始化失败
 */
define('ERR_XEMAC_INIT_FAILURE',                 1002 ); /* hex:0x3EA*/

/* SPI初始化失败
 */
define('ERR_PSSPI_INIT_FAILURE',                 1003 ); /* hex:0x3EB*/

/* 振镜通讯超时
 */
define('ERR_MOTOR_TIMEOUT',                      1004 ); /* hex:0x3EC*/

/* EDFA模块初始化失败
 */
define('ERR_EDFA_INIT_FAILURE',                  1005 ); /* hex:0x3ED*/

/* LMK04826模块初始化失败
 */
define('ERR_LMK04826_INIT_FAILURE',              1006 ); /* hex:0x3EE*/

/* LMK04826锁失败
 */
define('ERR_LMK04826_LOCK_FAILURE',              1007 ); /* hex:0x3EF*/

/* AFE模块初始化失败
 */
define('ERR_AFE_INIT_FAILURE',                   1008 ); /* hex:0x3F0*/

/* DMA模块初始化失败
 */
define('ERR_DMA_INIT_FAILURE',                   1009 ); /* hex:0x3F1*/

/* UDP通道初始化失败
 */
define('ERR_UDP_CHANNEL_INIT_FAILURE',           1010 ); /* hex:0x3F2*/

/************FPGA专用错误定义************/





