<?php
/* 
** # DO NOT EDIT THIS FILE!  
** # Auto generated from: 
** # D:\t\17.LARK\00.doc\03.HMI协议
** # 2024/5/28 10:39:44 
**/





/************HOST基础************/
/* @brief rev
 * @param data1(4byte)-  @default [ 0 ]
 */
define('REG_REV0',                               1 ); /*RW*/

/* @brief NumberOfTrailingFrames
 * @param data1(4byte)-  @default [ 0 ]
 */
define('REG_TRAILING_FRAME_NUM',                 2 ); /*RW*/

/* @brief Num of FiringSkip
 * @param data1(4byte)-  @default [ 0 ]
 */
define('REG_DEFAULT_FIRING_SKIP_NUM',            3 ); /*RW*/

/* @brief angle compensation-20221205
 * @param data1(4byte)-  @default [ 0 ]
 */
define('REG_LIDAR_PARAM1',                       4 ); /*RW*/

/* @brief start bin-20221205
 * @param data1(4byte)-  @default [ 0 ]
 */
define('REG_LIDAR_PARAM2',                       5 ); /*RW*/

/* @brief 雷达返回的速度最大门限，0则忽略
 * @param data1(4byte)-  @default [ 0 ]
 */
define('REG_LIDAR_VELOCITY_MAX',                 6 ); /*RW*/

/* @brief 雷达返回的距离最大门限，0则忽略
 * @param data1(4byte)-  @default [ 0 ]
 */
define('REG_LIDAR_DISTANCE_MAX',                 7 ); /*RW*/

/* @brief 雷达SNR最小门限，0则忽略
 * @param data1(4byte)-  @default [ 0 ]
 */
define('REG_LIDAR_SNR_MIN',                      8 ); /*RW*/

/* @brief LidarParamEncMulLays,TBD
 * @param data1(4byte)-  @default [ 0 ]
 */
define('REG_LIDAR_PARAM_ENC_MUL_LAYS',           9 ); /*RW*/

/* @brief DIS_OFF,TBD-待定义(20221009)
 * @param data1(4byte)-  @default [ 0 ]
 */
define('REG_LIDAR_DIS_OFF',                      10 ); /*RW*/

/* @brief msflag?TBD-待定义(20221009)
 * @param data1(4byte)-  @default [ 0 ]
 */
define('REG_LIDAR_MSFLAG',                       11 ); /*RW*/

/* @brief 可调节显示offset
 * @param data1(4byte)-  @default [ 0 ]
 */
define('REG_LIDAR_DISPLAY_OFFSET',               12 ); /*RW*/

/* @brief 系统工作状态记录使能掩码，上层存储到CSV
 *  b0-记录电压
 *  b1-记录温度
 *  b2-记录网络
 *  b3-原始数据(fft,power)
 *  b4-实时距离
 * @param data1(4byte)-  @default [0]
 */
define('REG_RECORD_FLAG',                        13 ); /*RW*/

/* @brief 数据记录文件门限，默认20W，单位：行
 * @param data1(4byte)-  @default [200000]
 */
define('REG_RECORD_LINE_LIMIT',                  14 ); /*RW*/

/* @brief 数据记录文件门限，默认180，单位：秒
 * @param data1(4byte)-  @default [180]
 */
define('REG_RECORD_TIME_LIMIT',                  15 ); /*RW*/

/* @brief 数据记录文件门限，默认64M，单位：M字节
 * @param data1(4byte)-  @default [64]
 */
define('REG_RECORD_SIZE_LIMIT',                  16 ); /*RW*/

/* @brief 图表视图缓存大小
 * @param data1(4byte)-  @default [ 0 ]
 */
define('REG_CHART_BUF_SIZE',                     17 ); /*RW*/

/* @brief 产品对应的laser数量
 *  FMLB:4
 *  LARK:8(默认)
 * @param data1(4byte)-  @default [ 0 ]
 */
define('REG_LASER_NUM',                          18 ); /*RW*/

/* @brief UDP日志输出
 * @param data1(4byte)-  @default [ 0 ]
 */
define('REG_UDP_LOG_ENABLE',                     19 ); /*RW*/


/* @brief Map Parameters
 * @param data1(4byte)-  @default [ 0 ]
 */
define('REG_SLAM_REG_BASE',                      30 ); /*R*/

/* @brief REG_SLAM_LOCALMAP_SIZE
 * @param data1(4byte)-  @default [ 0 ]
 */
define('REG_SLAM_LOCALMAP_SIZE',                 31 ); /*RW*/

/* @brief REG_SLAM_MOTION_VELOCITY_X
 * @param data1(4byte)-  @default [ 0 ]
 */
define('REG_SLAM_MOTION_VELOCITY_X',             32 ); /*RW*/

/* @brief REG_SLAM_MOTION_VELOCITY_Y
 * @param data1(4byte)-  @default [ 0 ]
 */
define('REG_SLAM_MOTION_VELOCITY_Y',             33 ); /*RW*/

/* @brief REG_SLAM_MOTION_VELOCITY_Z
 * @param data1(4byte)-  @default [ 0 ]
 */
define('REG_SLAM_MOTION_VELOCITY_Z',             34 ); /*RW*/


/* @brief select laser1
 * @param data1(4byte)-  @default [ 0 ]
 */
define('REG_STATE_LIDAR_LISER1',                 70 ); /*RW*/

/* @brief select laser2
 * @param data1(4byte)-  @default [ 0 ]
 */
define('REG_STATE_LIDAR_LISER2',                 71 ); /*RW*/

/* @brief select laser3
 * @param data1(4byte)-  @default [ 0 ]
 */
define('REG_STATE_LIDAR_LISER3',                 72 ); /*RW*/

/* @brief select laser4
 * @param data1(4byte)-  @default [ 0 ]
 */
define('REG_STATE_LIDAR_LISER4',                 73 ); /*RW*/

/* @brief select laser5
 * @param data1(4byte)-  @default [ 0 ]
 */
define('REG_STATE_LIDAR_LISER5',                 74 ); /*RW*/

/* @brief select laser6
 * @param data1(4byte)-  @default [ 0 ]
 */
define('REG_STATE_LIDAR_LISER6',                 75 ); /*RW*/

/* @brief select laser7
 * @param data1(4byte)-  @default [ 0 ]
 */
define('REG_STATE_LIDAR_LISER7',                 76 ); /*RW*/

/* @brief select laser8
 * @param data1(4byte)-  @default [ 0 ]
 */
define('REG_STATE_LIDAR_LISER8',                 77 ); /*RW*/




/* @brief MV2监视雷达IPv4地址
 * @param data1(4byte)-  @default [ 0 ]
 */
define('REG_VIEW_LIDAR_IP',                      80 ); /*RW*/

/* @brief MV2监视雷达IPv4端口
 * @param data1(4byte)-  @default [ 0 ]
 */
define('REG_VIEW_LIDAR_PORT',                    81 ); /*RW*/

/* @brief 视图点大小,单位:0.1,
 *  默认1.0
 * @param data1(4byte)-  @default [ 0 ]
 */
define('REG_VIEW_POINT_SIZE',                    82 ); /*RW*/

/* @brief 播放控制, @see PLAY_CTRL_E
 * @param data1(4byte)-  @default [ 0 ]
 */
define('REG_VIEW_PLAY_CTRL',                     83 ); /*RW*/

/* @brief bit0:不显示笛卡尔坐标
 *  bit1:不显示极坐标
 *  bit2:不显示文字
 * @param data1(4byte)-  @default [ 0 ]
 */
define('REG_VIEW_GRID_DISABLE',                  84 ); /*RW*/

/* @brief 左视图默认显示的点云帧
 * @param data1(4byte)-  @default [ 0 ]
 */
define('REG_ACTIVE_FRAME_TAG_VIEW0',             85 ); /*RW*/

/* @brief 右视图默认显示的点云帧
 * @param data1(4byte)-  @default [ 0 ]
 */
define('REG_ACTIVE_FRAME_TAG_VIEW1',             86 ); /*RW*/

/* @brief 左视图默认显示的字段
 * @param data1(4byte)-  @default [ 0 ]
 */
define('REG_ACTIVE_FIELD_VIEW0',                 87 ); /*RW*/

/* @brief 右视图默认显示的字段
 * @param data1(4byte)-  @default [ 0 ]
 */
define('REG_ACTIVE_FIELD_VIEW1',                 88 ); /*RW*/

/* @brief camera pos x,单位:0.001
 * @param data1(4byte)-  @default [ 0 ]
 */
define('REG_CAMERA_POS_X',                       89 ); /*RW*/

/* @brief camera pos y,单位:0.001
 * @param data1(4byte)-  @default [ 0 ]
 */
define('REG_CAMERA_POS_Y',                       90 ); /*RW*/

/* @brief camera pos z,单位:0.001
 * @param data1(4byte)-  @default [ 0 ]
 */
define('REG_CAMERA_POS_Z',                       91 ); /*RW*/

/* @brief camera view::x,单位:0.001
 * @param data1(4byte)-  @default [ 0 ]
 */
define('REG_CAMERA_VIEW_X',                      92 ); /*RW*/

/* @brief camera view::y,单位:0.001
 * @param data1(4byte)-  @default [ 0 ]
 */
define('REG_CAMERA_VIEW_Y',                      93 ); /*RW*/

/* @brief camera view::z,单位:0.001
 * @param data1(4byte)-  @default [ 0 ]
 */
define('REG_CAMERA_VIEW_Z',                      94 ); /*RW*/

/* @brief camera up::x,单位:0.001
 * @param data1(4byte)-  @default [ 0 ]
 */
define('REG_CAMERA_UP_X',                        95 ); /*RW*/

/* @brief camera up::y,单位:0.001
 * @param data1(4byte)-  @default [ 0 ]
 */
define('REG_CAMERA_UP_Y',                        96 ); /*RW*/

/* @brief camera up::z,单位:0.001
 * @param data1(4byte)-  @default [ 0 ]
 */
define('REG_CAMERA_UP_Z',                        97 ); /*RW*/

/* @brief 选择区域ROI X0
 *  注意需要与视图绑定
 * @param data1(4byte)-  @default [ 0 ]
 */
define('REG_SELECT_ROI_X0',                      98 ); /*RW*/

/* @brief 选择区域ROI Y0
 * @param data1(4byte)-  @default [ 0 ]
 */
define('REG_SELECT_ROI_Y0',                      99 ); /*RW*/

/* @brief 选择区域ROI X1
 * @param data1(4byte)-  @default [ 0 ]
 */
define('REG_SELECT_ROI_X1',                      100 ); /*RW*/

/* @brief 选择区域ROI Y1
 * @param data1(4byte)-  @default [ 0 ]
 */
define('REG_SELECT_ROI_Y1',                      101 ); /*RW*/

/* @brief 选择区域叠加使能
 * @param data1(4byte)-  @default [ 0 ]
 */
define('REG_SELECT_ROI_OVERLAP_ENABLE',          102 ); /*RW*/

/* @brief 选择区域叠加深度
 * @param data1(4byte)-  @default [ 0 ]
 */
define('REG_SELECT_ROI_OVERLAP_DEPTH',           103 ); /*RW*/

/* @brief UDP点云转发输出, @see HOST_POINTS_PORT
 * @param data1(4byte)-  @default [ 0 ]
 */
define('REG_PCD_FORWARD_TYPE',                   104 ); /*RW*/

/* @brief UDP点云转发输出使能
 * @param data1(4byte)-  @default [ 0 ]
 */
define('REG_PCD_FORWARD_ENABLE',                 105 ); /*RW*/

/* @brief PCAP GUID-自动化测试专用
 * @param data1(4byte)-  @default [ 0 ]
 */
define('REG_PCAP_GUID',                          106 ); /*RW*/

/* @brief PCAP点数量-自动化测试专用
 * @param data1(4byte)-  @default [ 0 ]
 */
define('REG_PCAP_PT_NUM',                        107 ); /*RW*/

/* @brief PCAP帧数量-自动化测试专用
 * @param data1(4byte)-  @default [ 0 ]
 */
define('REG_PCAP_FRAME_NUM',                     108 ); /*RW*/

/* @brief spreadsheet视图默认显示的点云帧
 * @param data1(4byte)-  @default [ 0 ]
 */
define('REG_SPREADSHEET_FRAME_TAG',              109 ); /*RW*/

/* @brief 速度视图显示范围，单位1，默认10，[-10, 10]
 * @param data1(4byte)-  @default [ 0 ]
 */
define('REG_VELOCITY_RENDER_RANGE',              110 ); /*RW*/

/* @brief 速度视图显示步长，单位0.1，默认0.5
 * @param data1(4byte)-  @default [ 0 ]
 */
define('REG_VELOCITY_RENDER_STEP',               111 ); /*RW*/




/************设备统计信息************/
/* @brief 软件版本号
 * @param data1(4byte)-  @default [ 0 ]
 */
define('REG_HOST_VERSION',                       129 ); /*R*/

/* @brief 通道数量，最大192
 * @param data1(4byte)-  @default [ 64 ]
 */
define('REG_CHANNEL_COUNT',                      130 ); /*R*/

/* @brief filter key result
 * @param data1(4byte)-  @default [ 0 ]
 */
define('REG_OVERLAP_KEYPOINT_NUM',               131 ); /*R*/

/* @brief icp perfermance
 * @param data1(4byte)-  @default [ 0 ]
 */
define('REG_OVERLAP_ICP_TICKS',                  132 ); /*R*/









/* 寄存器总数量 */
define('HOST_REG_CNT',           133 );




