<?php
/* 
** # DO NOT EDIT THIS FILE!  
** # Auto generated from: 
** # D:\t\17.LARK\00.doc\03.HMI协议
** # 2023/12/19 17:12:46 
**/





/************IAP写参数************/
/* @brief IAP流程控制，详见代码
 *    ICE_PREPARE = 0xa1, // 准备iap
 *    ICE_START,          // 数据传输
 *    ICE_TERM,           // 流程中断
 *    ICE_EOF,            // 传输完毕
 *    ICE_VERIFY,         // 执行校验
 *    ICE_PROGRAM,          // 执行写入
 *    ICE_REBOOT,         // 执行重启
 *    ICE_BKBOOT, // 备份启动
 * @param data1(4byte)-  @default [0]
 */
define('REG_IAP_CTRL',                           1 ); /*RW*/

/* @brief IAP应用功能定义
 *  [7:0] fileType：
 *    *1-IFE_BOOTIMG: 默认升级完整镜像（完整版本，含FPGA）；
 *    *2-IFE_CONFIG:烧写更新配置区段；
 *    *3-IFE_FPGA：单独升级fpga（xilinx为bin格式，使用write_cfgmem命令转换.bit到.bin），不写入flash，仅在内存运行，用于FPGA版本调试；
 *    *11-IFE_GLODEN: 烧写更新bsp备份镜像（慎用）；
 *  [31:8] Rev
 * @param data1(4byte)-  @default [0]
 */
define('REG_IAP_FILE_TYPE',                      2 ); /*RW*/

/* @brief IAP文件大小，由host写入
 * @param data1(4byte)-  @default [0]
 */
define('REG_IAP_FILE_SIZE',                      3 ); /*RW*/

/* @brief IAP文件校验值-在host写入
 * @param data1(4byte)-  @default [0]
 */
define('REG_IAP_FILE_CRC',                       4 ); /*RW*/

/* @brief FLASH更新静默等待时长，默认45s
 *  此时可能会中断通讯
 * @param data1(4byte)-  @default [45]
 */
define('REG_IAP_FLUSH_TIMEOUT',                  5 ); /*RW*/








/************只读信息************/
/* @brief 返回IAP版本信息，默认为0(使用旧版v1）
 *    最新为v2(20230926)
 * @param data1(4byte)-  @default [0]
 */
define('REG_IAP_VERSION',                        129 ); /*R*/

/* @brief 返回IAP执行状态
 *  [7:0] 当前状态，同REG_IAP_CTRL定义
 *    ISE1_IDLE = 0,        // 空闲状态
 *    ISE1_READY = 0xc1,    // 准备完毕
 *    ISE1_TRANSING,        // 正在传输
 *    ISE1_WAIT_RESEND,     // 需要重传
 *    ISE1_FINISH,          // 传输完毕
 *    ISE1_VERIFYING,       // 执行校验
 *    ISE1_VERIFY_OK,       // 校验OK
 *    ISE1_FLUSHING,        // 执行写入
 *    ISE1_FLUSH_OK,        // 写入OK
 *    ISE1_ERROR,           // 遇到错误
 *  [15:8]  异常flag
 *    0x1-需要重传，读取REG_IAP_RESEND_OFFSET
 *    0x2-遇到错误，
 *  [23:16] 进度状态，百分比
 *  [31:24] rev
 * @param data1(4byte)-  @default [0]
 */
define('REG_IAP_STATUS',                         130 ); /*R*/

/* @brief IAP块大小
 * @param data1(4byte)-  @default [0]
 */
define('REG_IAP_FRAME_SIZE',                     131 ); /*RW*/

/* @brief 重传字节偏移，冗余验证重传地址
 * @param data1(4byte)-  @default [0]
 */
define('REG_IAP_RESEND_OFFSET',                  132 ); /*RC*/

/* @brief 已接收帧序记录
 * @param data1(4byte)-  @default [0]
 */
define('REG_IAP_RECV_FRAMES',                    133 ); /*R*/

/* @brief IAP通道已接收的字节数
 * @param data1(4byte)-  @default [0]
 */
define('REG_IAP_RECV_BYTES',                     134 ); /*R*/

/* @brief IAP通道已发送的字节数
 * @param data1(4byte)-  @default [0]
 */
define('REG_IAP_SEND_BYTES',                     135 ); /*R*/

/* @brief IAP TCP连接数量
 * @param data1(4byte)-  @default [0]
 */
define('REG_IAP_CONNTECTIONS',                   136 ); /*R*/

/* @brief IAP接收的最大文件限制
 * @param data1(4byte)-  @default [0]
 */
define('REG_IAP_MAX_FILE_SIZE',                  137 ); /*R*/

/* @brief IAP接收缓存有效数据量
 * @param data1(4byte)-  @default [0]
 */
define('REG_IAP_RX_BUF_VALID',                   138 ); /*R*/












/* 寄存器总数量 */
define('IAP_REG_CNT',            139 );




