<?php
/* 
** # DO NOT EDIT THIS FILE!  
** # Auto generated from: 
** # D:\t\13.FML\00.doc\03.HMI协议
** # 2023/7/18 10:46:58 
**/





/************设备IP类************/
/* @brief 主机IP地址，用于点云及其他数据上传
 * @param data1(4byte)-  @default [192.168.1.111]
 */
define('REG_HOST_IP',                            1 ); /*RW*/

/* @brief DHCP使能
 * @param data1(4byte)-1-enable，0-disable  @default [0]
 */
define('REG_DHCP_ENABLE',                        2 ); /*RW*/

/* @brief 静态IP设置
 * @param data1(4byte)-IPv4：4字节IP设置  @default [192.168.1.10]
 */
define('REG_DEVICE_IP',                          3 ); /*RW*/

/* @brief 子网掩码
 * @param data1(4byte)-IPv4：4字节子网掩码  @default [255.255.255.0]
 */
define('REG_NET_MASK',                           4 ); /*RW*/

/* @brief 网关
 * @param data1(4byte)-IPv4：4字节网关  @default [192.168.1.1]
 */
define('REG_NET_GATEWAY',                        5 ); /*RW*/

/* @brief DNS设置
 * @param data1(4byte)-IPv4：4字节DNS  @default []
 */
define('REG_NET_DNS',                            6 ); /*RW*/

/* @brief MAC地址byte[0-3]
 * @param data1(4byte)-MAC地址byte[0-3]  @default []
 */
define('REG_NET_MAC0',                           7 ); /*RW*/

/* @brief MAC地址byte[4-5]
 * @param data1(4byte)-MAC地址byte[4-5]  @default []
 */
define('REG_NET_MAC1',                           8 ); /*RW*/

/* @brief 静态IPv6设置byte[0-3]
 * @param data1(4byte)-静态IPv6设置byte[0-3]  @default []
 */
define('REG_STATIC_IPv6_0',                      9 ); /*RW*/

/* @brief 静态IPv6设置byte[4-7]
 * @param data1(4byte)-静态IPv6设置byte[4-7]  @default []
 */
define('REG_STATIC_IPv6_1',                      10 ); /*RW*/

/* @brief 静态IPv6设置byte[8-11]
 * @param data1(4byte)-静态IPv6设置byte[8-11]  @default []
 */
define('REG_STATIC_IPv6_2',                      11 ); /*RW*/

/* @brief 静态IPv6设置byte[12-15]
 * @param data1(4byte)-静态IPv6设置byte[12-15]  @default []
 */
define('REG_STATIC_IPv6_3',                      12 ); /*RW*/












/************用户信息类************/
/* @brief 存储管理员用户名称-前4byte(最大8个字符)
 * @param data1(4byte)-  @default ['admi']
 */
define('REG_ADMIN_NAME0',                        111 ); /*RW*/

/* @brief 存储管理员用户名称-后4byte
 * @param data1(4byte)-  @default ['n']
 */
define('REG_ADMIN_NAME1',                        112 ); /*RW*/

/* @brief 存储管理员用户密码-前4byte(最大8个字符)
 * @param data1(4byte)-  @default []
 */
define('REG_ADMIN_PWD0',                         113 ); /*RW*/

/* @brief 存储管理员用户密码-后4byte
 * @param data1(4byte)-  @default []
 */
define('REG_ADMIN_PWD1',                         114 ); /*RW*/

/* @brief 存储一般用户0名称-前4byte(最大8个字符)
 * @param data1(4byte)-  @default ['user']
 */
define('REG_USER0_NAME0',                        115 ); /*RW*/

/* @brief 存储一般用户0名称-后4byte
 * @param data1(4byte)-  @default ['1']
 */
define('REG_USER0_NAME1',                        116 ); /*RW*/

/* @brief 存储一般用户0密码-前4byte(最大8个字符)
 * @param data1(4byte)-  @default ['more']
 */
define('REG_USER0_PWD0',                         117 ); /*RW*/

/* @brief 存储一般用户0密码-后4byte
 * @param data1(4byte)-  @default ['']
 */
define('REG_USER0_PWD1',                         118 ); /*RW*/

/* @brief 存储一般用户1名称-前4byte(最大8个字符)
 * @param data1(4byte)-  @default ['user']
 */
define('REG_USER1_NAME0',                        119 ); /*RW*/

/* @brief 存储一般用户1名称-后4byte
 * @param data1(4byte)-  @default ['2']
 */
define('REG_USER1_NAME1',                        120 ); /*RW*/

/* @brief 存储一般用户1密码-前4byte(最大8个字符)
 * @param data1(4byte)-  @default ['more']
 */
define('REG_USER1_PWD0',                         121 ); /*RW*/

/* @brief 存储一般用户1密码-后4byte
 * @param data1(4byte)-  @default ['']
 */
define('REG_USER1_PWD1',                         122 ); /*RW*/



/************设备统计信息************/
/* @brief Lwip版本号
 * @param data1(4byte)-  @default []
 */
define('REG_LWIP_VERSION',                       129 ); /*R*/

/* @brief 最新错误
 * @param data1(4byte)-  @default []
 */
define('REG_LWIP_LAST_ERROR',                    130 ); /*R*/






/* 寄存器总数量 */
define('LWIP_REG_CNT',           131 );




