<?php
/* 
** # DO NOT EDIT THIS FILE!  
** # Auto generated from: 
** # D:\doc\04.HMI协议（LARK）
** # 2024/6/14 16:04:51 
**/





/************基础参数配置************/
/* @brief 通道表尺寸，最大值：8
 *  FMLB:4
 *  LARK-16HZ:8(20240424)
 *  LARK-32HZ:8(20240424)
 * @param data1(4byte)-  @default [8]
 */
define('REG_FOV_LUT_SIZE',                       1 ); /*RW*/

/* @brief 真角度映射表尺寸，最大值：32
 *  FMLB:16
 *  LARK-16HZ:32(20240424)
 *  LARK-32HZ:32(20240424)
 * @param data1(4byte)-  @default [32]
 */
define('REG_F2R_LUT_SIZE',                       2 ); /*RW*/

/* @brief 三角函数查找表尺寸，默认：4096
 * @param data1(4byte)-  @default [4096]
 */
define('REG_TRIANGLE_LUT_SIZE',                  3 ); /*RW*/

/* @brief 真角度映射表尺寸，最大值：32
 *  FMLB:16
 *  LARK-16HZ:32(20240424)
 *  LARK-32HZ:32(20240424)
 * @param data1(4byte)-  @default [32]
 */
define('REG_PATTERN_SIZE',                       4 ); /*RW*/

/* @brief 水平角度最小值，
 *  FMLB:默认9' --a * (360 / 19200)
 *  LARK16: 360
 * @param data1(4byte)-  @default [9]
 */
define('REG_HORZ_LEFT',                          5 ); /*RW*/

/* @brief 水平角度最大值，默认81'
 *  FMLB:
 *  LARK16: 3240
 * @param data1(4byte)-  @default [81]
 */
define('REG_HORZ_RIGHT',                         6 ); /*RW*/

/* @brief 水平角度编码器分辨率，默认19200
 * @param data1(4byte)-  @default [19200]
 */
define('REG_HORZ_RESOLUTION',                    7 ); /*RW*/

/* @brief 垂直角度公式：y=kx+a的k值，单位：1e-9
 * @param data1(4byte)-  @default [0]
 */
define('REG_VERT_FACTOR_K',                      8 ); /*RW*/

/* @brief 垂直角度公式：y=kx+a的a值，单位：1e-6
 * @param data1(4byte)-  @default [0]
 */
define('REG_VERT_FACTOR_A',                      9 ); /*RW*/

/* @brief 多普勒因子，与转速相关
 * @param data1(4byte)-  @default [0]
 */
define('REG_DOPPLER_FACTOR',                     10 ); /*RW*/

/* @brief fake or real类型选择
 * @param data1(4byte)-  @default [0]
 */
define('REG_F2R_SELECT',                         11 ); /*RW*/

/* @brief LASERID映射表尺寸，默认：256
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASER_ID_LUT_SIZE',                  12 ); /*RW*/

/* @brief 振镜转轴在y方向上的夹角，单位：1e-6
 *  LARK32:默认31.6355;
 * @param data1(4byte)-  @default [0]
 */
define('REG_GLOV_C_FACTOR',                      13 ); /*RW*/

/* @brief 晶体至空气折射率，单位：1e-6
 *  LARK32:默认-46.7284（补角：-43.27164）
 * @param data1(4byte)-  @default [0]
 */
define('REG_PRIMS3_ANGLE',                       14 ); /*RW*/

/* @brief 空气至晶体折射率，单位：1e-6
 *  LARK32:默认1.4416
 * @param data1(4byte)-  @default [0]
 */
define('REG_WEDGE_REFACTIVE',                    15 ); /*RW*/

/* @brief 无符号，棱镜半径，下发FPGA，
 *  默认1669
 * @param data1(4byte)-  @default [1669]
 */
define('REG_POLYGON_RADIUS_CAL',                 16 ); /*RW*/

/* @brief 有符号，棱镜中心点X坐标，下发FPGA，
 *  默认-4110
 * @param data1(4byte)-  @default [-4110]
 */
define('REG_POLYGON_AXESX_CAL',                  17 ); /*RW*/

/* @brief 有符号，棱镜中心点Y坐标，下发FPGA，
 *  默认-2001
 * @param data1(4byte)-  @default [-2001]
 */
define('REG_POLYGON_AXESY_CAL',                  18 ); /*RW*/

/* @brief 有符号，棱镜旋转半径，单位：1e-6
 * @param data1(4byte)-  @default [25460]
 */
define('REG_POLYGON_RADIUS_REAL',                19 ); /*RW*/

/* @brief 有符号，棱镜轴心X坐标，单位：1e-6
 * @param data1(4byte)-  @default [-62710]
 */
define('REG_POLYGON_AXESX_REAL',                 20 ); /*RW*/

/* @brief 有符号，棱镜轴心Y坐标，单位：1e-6
 * @param data1(4byte)-  @default [-30540]
 */
define('REG_POLYGON_AXESY_REAL',                 21 ); /*RW*/

/* @brief 有符号，振镜轴心X坐标，单位：1e-6
 * @param data1(4byte)-  @default [0]
 */
define('REG_GALVO_AXESX_REAL',                   22 ); /*RW*/

/* @brief 有符号，振镜初始位置，单位：1e-6
 * @param data1(4byte)-  @default [31635500]
 */
define('REG_GALVO_INIT_POS',                     23 ); /*RW*/











/************通道FOV（入射角）值基地址-最大8（20240424）************/
/* @brief ch0通道fov值，单位：1e-6（光学提供）
 * @param data1(4byte)-  @default [1800000]
 */
define('REG_FOV_CH0',                            64 ); /*RW*/

/* @brief ch1通道fov值，单位：1e-6（光学提供）
 * @param data1(4byte)-  @default [600000]
 */
define('REG_FOV_CH1',                            65 ); /*RW*/

/* @brief ch2通道fov值，单位：1e-6（光学提供）
 * @param data1(4byte)-  @default [-600000]
 */
define('REG_FOV_CH2',                            66 ); /*RW*/

/* @brief ch3通道fov值，单位：1e-6（光学提供）
 * @param data1(4byte)-  @default [-1800000]
 */
define('REG_FOV_CH3',                            67 ); /*RW*/

/* @brief ch4通道fov值，单位：1e-6（光学提供）
 * @param data1(4byte)-  @default [ 0 ]
 */
define('REG_FOV_CH4',                            68 ); /*RW*/

/* @brief ch5通道fov值，单位：1e-6（光学提供）
 * @param data1(4byte)-  @default [ 0 ]
 */
define('REG_FOV_CH5',                            69 ); /*RW*/

/* @brief ch6通道fov值，单位：1e-6（光学提供）
 * @param data1(4byte)-  @default [ 0 ]
 */
define('REG_FOV_CH6',                            70 ); /*RW*/

/* @brief ch7通道fov值，单位：1e-6（光学提供）
 * @param data1(4byte)-  @default [ 0 ]
 */
define('REG_FOV_CH7',                            71 ); /*RW*/


/************真假角度查找表基地址-最大32（20240424）************/
/* @brief fake or real角度查找表V0
 * @param data1(4byte)-  @default [0]
 */
define('REG_F2R_LUT_V0',                         128 ); /*RW*/

/* @brief fake or real角度查找表V1
 * @param data1(4byte)-  @default [0]
 */
define('REG_F2R_LUT_V1',                         129 ); /*RW*/

/* @brief fake or real角度查找表V2
 * @param data1(4byte)-  @default [0]
 */
define('REG_F2R_LUT_V2',                         130 ); /*RW*/

/* @brief fake or real角度查找表V3
 * @param data1(4byte)-  @default [0]
 */
define('REG_F2R_LUT_V3',                         131 ); /*RW*/

/* @brief fake or real角度查找表V4
 * @param data1(4byte)-  @default [0]
 */
define('REG_F2R_LUT_V4',                         132 ); /*RW*/

/* @brief fake or real角度查找表V5
 * @param data1(4byte)-  @default [0]
 */
define('REG_F2R_LUT_V5',                         133 ); /*RW*/

/* @brief fake or real角度查找表V6
 * @param data1(4byte)-  @default [0]
 */
define('REG_F2R_LUT_V6',                         134 ); /*RW*/

/* @brief fake or real角度查找表V7
 * @param data1(4byte)-  @default [0]
 */
define('REG_F2R_LUT_V7',                         135 ); /*RW*/

/* @brief fake or real角度查找表V8
 * @param data1(4byte)-  @default [0]
 */
define('REG_F2R_LUT_V8',                         136 ); /*RW*/

/* @brief fake or real角度查找表V9
 * @param data1(4byte)-  @default [0]
 */
define('REG_F2R_LUT_V9',                         137 ); /*RW*/

/* @brief fake or real角度查找表V10
 * @param data1(4byte)-  @default [0]
 */
define('REG_F2R_LUT_V10',                        138 ); /*RW*/

/* @brief fake or real角度查找表V11
 * @param data1(4byte)-  @default [0]
 */
define('REG_F2R_LUT_V11',                        139 ); /*RW*/

/* @brief fake or real角度查找表V12
 * @param data1(4byte)-  @default [0]
 */
define('REG_F2R_LUT_V12',                        140 ); /*RW*/

/* @brief fake or real角度查找表V13
 * @param data1(4byte)-  @default [0]
 */
define('REG_F2R_LUT_V13',                        141 ); /*RW*/

/* @brief fake or real角度查找表V14
 * @param data1(4byte)-  @default [0]
 */
define('REG_F2R_LUT_V14',                        142 ); /*RW*/

/* @brief fake or real角度查找表V15
 * @param data1(4byte)-  @default [0]
 */
define('REG_F2R_LUT_V15',                        143 ); /*RW*/

/* @brief fake or real角度查找表V16
 * @param data1(4byte)-  @default [0]
 */
define('REG_F2R_LUT_V16',                        144 ); /*RW*/

/* @brief fake or real角度查找表V17
 * @param data1(4byte)-  @default [0]
 */
define('REG_F2R_LUT_V17',                        145 ); /*RW*/

/* @brief fake or real角度查找表V18
 * @param data1(4byte)-  @default [0]
 */
define('REG_F2R_LUT_V18',                        146 ); /*RW*/

/* @brief fake or real角度查找表V19
 * @param data1(4byte)-  @default [0]
 */
define('REG_F2R_LUT_V19',                        147 ); /*RW*/

/* @brief fake or real角度查找表V20
 * @param data1(4byte)-  @default [0]
 */
define('REG_F2R_LUT_V20',                        148 ); /*RW*/

/* @brief fake or real角度查找表V21
 * @param data1(4byte)-  @default [0]
 */
define('REG_F2R_LUT_V21',                        149 ); /*RW*/

/* @brief fake or real角度查找表V22
 * @param data1(4byte)-  @default [0]
 */
define('REG_F2R_LUT_V22',                        150 ); /*RW*/

/* @brief fake or real角度查找表V23
 * @param data1(4byte)-  @default [0]
 */
define('REG_F2R_LUT_V23',                        151 ); /*RW*/

/* @brief fake or real角度查找表V24
 * @param data1(4byte)-  @default [0]
 */
define('REG_F2R_LUT_V24',                        152 ); /*RW*/

/* @brief fake or real角度查找表V25
 * @param data1(4byte)-  @default [0]
 */
define('REG_F2R_LUT_V25',                        153 ); /*RW*/

/* @brief fake or real角度查找表V26
 * @param data1(4byte)-  @default [0]
 */
define('REG_F2R_LUT_V26',                        154 ); /*RW*/

/* @brief fake or real角度查找表V27
 * @param data1(4byte)-  @default [0]
 */
define('REG_F2R_LUT_V27',                        155 ); /*RW*/

/* @brief fake or real角度查找表V28
 * @param data1(4byte)-  @default [0]
 */
define('REG_F2R_LUT_V28',                        156 ); /*RW*/

/* @brief fake or real角度查找表V29
 * @param data1(4byte)-  @default [0]
 */
define('REG_F2R_LUT_V29',                        157 ); /*RW*/

/* @brief fake or real角度查找表V30
 * @param data1(4byte)-  @default [0]
 */
define('REG_F2R_LUT_V30',                        158 ); /*RW*/

/* @brief fake or real角度查找表V31
 * @param data1(4byte)-  @default [0]
 */
define('REG_F2R_LUT_V31',                        159 ); /*RW*/



/************电机控制值地址(pattern)-最大32（20240424）************/
/* @brief Vmotor DAC V0
 * @param data1(4byte)-  @default [0]
 */
define('REG_PATTERN_LUT_V0',                     192 ); /*RW*/

/* @brief Vmotor DAC V1
 * @param data1(4byte)-  @default [0]
 */
define('REG_PATTERN_LUT_V1',                     193 ); /*RW*/

/* @brief Vmotor DAC V2
 * @param data1(4byte)-  @default [0]
 */
define('REG_PATTERN_LUT_V2',                     194 ); /*RW*/

/* @brief Vmotor DAC V3
 * @param data1(4byte)-  @default [0]
 */
define('REG_PATTERN_LUT_V3',                     195 ); /*RW*/

/* @brief Vmotor DAC V4
 * @param data1(4byte)-  @default [0]
 */
define('REG_PATTERN_LUT_V4',                     196 ); /*RW*/

/* @brief Vmotor DAC V5
 * @param data1(4byte)-  @default [0]
 */
define('REG_PATTERN_LUT_V5',                     197 ); /*RW*/

/* @brief Vmotor DAC V6
 * @param data1(4byte)-  @default [0]
 */
define('REG_PATTERN_LUT_V6',                     198 ); /*RW*/

/* @brief Vmotor DAC V7
 * @param data1(4byte)-  @default [0]
 */
define('REG_PATTERN_LUT_V7',                     199 ); /*RW*/

/* @brief Vmotor DAC V8
 * @param data1(4byte)-  @default [0]
 */
define('REG_PATTERN_LUT_V8',                     200 ); /*RW*/

/* @brief Vmotor DAC V9
 * @param data1(4byte)-  @default [0]
 */
define('REG_PATTERN_LUT_V9',                     201 ); /*RW*/

/* @brief Vmotor DAC V10
 * @param data1(4byte)-  @default [0]
 */
define('REG_PATTERN_LUT_V10',                    202 ); /*RW*/

/* @brief Vmotor DAC V11
 * @param data1(4byte)-  @default [0]
 */
define('REG_PATTERN_LUT_V11',                    203 ); /*RW*/

/* @brief Vmotor DAC V12
 * @param data1(4byte)-  @default [0]
 */
define('REG_PATTERN_LUT_V12',                    204 ); /*RW*/

/* @brief Vmotor DAC V13
 * @param data1(4byte)-  @default [0]
 */
define('REG_PATTERN_LUT_V13',                    205 ); /*RW*/

/* @brief Vmotor DAC V14
 * @param data1(4byte)-  @default [0]
 */
define('REG_PATTERN_LUT_V14',                    206 ); /*RW*/

/* @brief Vmotor DAC V15
 * @param data1(4byte)-  @default [0]
 */
define('REG_PATTERN_LUT_V15',                    207 ); /*RW*/

/* @brief Vmotor DAC V16
 * @param data1(4byte)-  @default [0]
 */
define('REG_PATTERN_LUT_V16',                    208 ); /*RW*/

/* @brief Vmotor DAC V17
 * @param data1(4byte)-  @default [0]
 */
define('REG_PATTERN_LUT_V17',                    209 ); /*RW*/

/* @brief Vmotor DAC V18
 * @param data1(4byte)-  @default [0]
 */
define('REG_PATTERN_LUT_V18',                    210 ); /*RW*/

/* @brief Vmotor DAC V19
 * @param data1(4byte)-  @default [0]
 */
define('REG_PATTERN_LUT_V19',                    211 ); /*RW*/

/* @brief Vmotor DAC V20
 * @param data1(4byte)-  @default [0]
 */
define('REG_PATTERN_LUT_V20',                    212 ); /*RW*/

/* @brief Vmotor DAC V21
 * @param data1(4byte)-  @default [0]
 */
define('REG_PATTERN_LUT_V21',                    213 ); /*RW*/

/* @brief Vmotor DAC V22
 * @param data1(4byte)-  @default [0]
 */
define('REG_PATTERN_LUT_V22',                    214 ); /*RW*/

/* @brief Vmotor DAC V23
 * @param data1(4byte)-  @default [0]
 */
define('REG_PATTERN_LUT_V23',                    215 ); /*RW*/

/* @brief Vmotor DAC V24
 * @param data1(4byte)-  @default [0]
 */
define('REG_PATTERN_LUT_V24',                    216 ); /*RW*/

/* @brief Vmotor DAC V25
 * @param data1(4byte)-  @default [0]
 */
define('REG_PATTERN_LUT_V25',                    217 ); /*RW*/

/* @brief Vmotor DAC V26
 * @param data1(4byte)-  @default [0]
 */
define('REG_PATTERN_LUT_V26',                    218 ); /*RW*/

/* @brief Vmotor DAC V27
 * @param data1(4byte)-  @default [0]
 */
define('REG_PATTERN_LUT_V27',                    219 ); /*RW*/

/* @brief Vmotor DAC V28
 * @param data1(4byte)-  @default [0]
 */
define('REG_PATTERN_LUT_V28',                    220 ); /*RW*/

/* @brief Vmotor DAC V29
 * @param data1(4byte)-  @default [0]
 */
define('REG_PATTERN_LUT_V29',                    221 ); /*RW*/

/* @brief Vmotor DAC V30
 * @param data1(4byte)-  @default [0]
 */
define('REG_PATTERN_LUT_V30',                    222 ); /*RW*/

/* @brief Vmotor DAC V31
 * @param data1(4byte)-  @default [0]
 */
define('REG_PATTERN_LUT_V31',                    223 ); /*RW*/



/************pid查找表基地址，最大16个-20240424************/
/* @brief pid查找表V0
 * @param data1(4byte)-  @default [0]
 */
define('REG_PID_LUT_V0',                         256 ); /*RW*/

/* @brief pid查找表V1
 * @param data1(4byte)-  @default [0]
 */
define('REG_PID_LUT_V1',                         257 ); /*RW*/

/* @brief pid查找表V2
 * @param data1(4byte)-  @default [0]
 */
define('REG_PID_LUT_V2',                         258 ); /*RW*/

/* @brief pid查找表V3
 * @param data1(4byte)-  @default [0]
 */
define('REG_PID_LUT_V3',                         259 ); /*RW*/

/* @brief pid查找表V4
 * @param data1(4byte)-  @default [0]
 */
define('REG_PID_LUT_V4',                         260 ); /*RW*/

/* @brief pid查找表V5
 * @param data1(4byte)-  @default [0]
 */
define('REG_PID_LUT_V5',                         261 ); /*RW*/

/* @brief pid查找表V6
 * @param data1(4byte)-  @default [0]
 */
define('REG_PID_LUT_V6',                         262 ); /*RW*/

/* @brief pid查找表V7
 * @param data1(4byte)-  @default [0]
 */
define('REG_PID_LUT_V7',                         263 ); /*RW*/

/* @brief pid查找表V8
 * @param data1(4byte)-  @default [0]
 */
define('REG_PID_LUT_V8',                         264 ); /*RW*/

/* @brief pid查找表V9
 * @param data1(4byte)-  @default [0]
 */
define('REG_PID_LUT_V9',                         265 ); /*RW*/

/* @brief pid查找表V10
 * @param data1(4byte)-  @default [0]
 */
define('REG_PID_LUT_V10',                        266 ); /*RW*/

/* @brief pid查找表V11
 * @param data1(4byte)-  @default [0]
 */
define('REG_PID_LUT_V11',                        267 ); /*RW*/

/* @brief pid查找表V12
 * @param data1(4byte)-  @default [0]
 */
define('REG_PID_LUT_V12',                        268 ); /*RW*/

/* @brief pid查找表V13
 * @param data1(4byte)-  @default [0]
 */
define('REG_PID_LUT_V13',                        269 ); /*RW*/

/* @brief pid查找表V14
 * @param data1(4byte)-  @default [0]
 */
define('REG_PID_LUT_V14',                        270 ); /*RW*/

/* @brief pid查找表V15
 * @param data1(4byte)-  @default [0]
 */
define('REG_PID_LUT_V15',                        271 ); /*RW*/




/************laserId查找表基地址-最大256个-20240424************/
/* @brief laserId查找表V0
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V0',                     512 ); /*RW*/

/* @brief laserId查找表V1
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V1',                     513 ); /*RW*/

/* @brief laserId查找表V2
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V2',                     514 ); /*RW*/

/* @brief laserId查找表V3
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V3',                     515 ); /*RW*/

/* @brief laserId查找表V4
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V4',                     516 ); /*RW*/

/* @brief laserId查找表V5
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V5',                     517 ); /*RW*/

/* @brief laserId查找表V6
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V6',                     518 ); /*RW*/

/* @brief laserId查找表V7
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V7',                     519 ); /*RW*/

/* @brief laserId查找表V8
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V8',                     520 ); /*RW*/

/* @brief laserId查找表V9
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V9',                     521 ); /*RW*/

/* @brief laserId查找表V10
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V10',                    522 ); /*RW*/

/* @brief laserId查找表V11
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V11',                    523 ); /*RW*/

/* @brief laserId查找表V12
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V12',                    524 ); /*RW*/

/* @brief laserId查找表V13
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V13',                    525 ); /*RW*/

/* @brief laserId查找表V14
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V14',                    526 ); /*RW*/

/* @brief laserId查找表V15
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V15',                    527 ); /*RW*/

/* @brief laserId查找表V16
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V16',                    528 ); /*RW*/

/* @brief laserId查找表V17
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V17',                    529 ); /*RW*/

/* @brief laserId查找表V18
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V18',                    530 ); /*RW*/

/* @brief laserId查找表V19
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V19',                    531 ); /*RW*/

/* @brief laserId查找表V20
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V20',                    532 ); /*RW*/

/* @brief laserId查找表V21
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V21',                    533 ); /*RW*/

/* @brief laserId查找表V22
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V22',                    534 ); /*RW*/

/* @brief laserId查找表V23
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V23',                    535 ); /*RW*/

/* @brief laserId查找表V24
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V24',                    536 ); /*RW*/

/* @brief laserId查找表V25
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V25',                    537 ); /*RW*/

/* @brief laserId查找表V26
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V26',                    538 ); /*RW*/

/* @brief laserId查找表V27
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V27',                    539 ); /*RW*/

/* @brief laserId查找表V28
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V28',                    540 ); /*RW*/

/* @brief laserId查找表V29
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V29',                    541 ); /*RW*/

/* @brief laserId查找表V30
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V30',                    542 ); /*RW*/

/* @brief laserId查找表V31
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V31',                    543 ); /*RW*/

/* @brief laserId查找表V32
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V32',                    544 ); /*RW*/

/* @brief laserId查找表V33
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V33',                    545 ); /*RW*/

/* @brief laserId查找表V34
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V34',                    546 ); /*RW*/

/* @brief laserId查找表V35
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V35',                    547 ); /*RW*/

/* @brief laserId查找表V36
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V36',                    548 ); /*RW*/

/* @brief laserId查找表V37
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V37',                    549 ); /*RW*/

/* @brief laserId查找表V38
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V38',                    550 ); /*RW*/

/* @brief laserId查找表V39
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V39',                    551 ); /*RW*/

/* @brief laserId查找表V40
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V40',                    552 ); /*RW*/

/* @brief laserId查找表V41
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V41',                    553 ); /*RW*/

/* @brief laserId查找表V42
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V42',                    554 ); /*RW*/

/* @brief laserId查找表V43
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V43',                    555 ); /*RW*/

/* @brief laserId查找表V44
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V44',                    556 ); /*RW*/

/* @brief laserId查找表V45
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V45',                    557 ); /*RW*/

/* @brief laserId查找表V46
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V46',                    558 ); /*RW*/

/* @brief laserId查找表V47
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V47',                    559 ); /*RW*/

/* @brief laserId查找表V48
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V48',                    560 ); /*RW*/

/* @brief laserId查找表V49
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V49',                    561 ); /*RW*/

/* @brief laserId查找表V50
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V50',                    562 ); /*RW*/

/* @brief laserId查找表V51
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V51',                    563 ); /*RW*/

/* @brief laserId查找表V52
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V52',                    564 ); /*RW*/

/* @brief laserId查找表V53
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V53',                    565 ); /*RW*/

/* @brief laserId查找表V54
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V54',                    566 ); /*RW*/

/* @brief laserId查找表V55
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V55',                    567 ); /*RW*/

/* @brief laserId查找表V56
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V56',                    568 ); /*RW*/

/* @brief laserId查找表V57
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V57',                    569 ); /*RW*/

/* @brief laserId查找表V58
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V58',                    570 ); /*RW*/

/* @brief laserId查找表V59
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V59',                    571 ); /*RW*/

/* @brief laserId查找表V60
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V60',                    572 ); /*RW*/

/* @brief laserId查找表V61
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V61',                    573 ); /*RW*/

/* @brief laserId查找表V62
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V62',                    574 ); /*RW*/

/* @brief laserId查找表V63
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V63',                    575 ); /*RW*/

/* @brief laserId查找表V64
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V64',                    576 ); /*RW*/

/* @brief laserId查找表V65
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V65',                    577 ); /*RW*/

/* @brief laserId查找表V66
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V66',                    578 ); /*RW*/

/* @brief laserId查找表V67
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V67',                    579 ); /*RW*/

/* @brief laserId查找表V68
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V68',                    580 ); /*RW*/

/* @brief laserId查找表V69
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V69',                    581 ); /*RW*/

/* @brief laserId查找表V70
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V70',                    582 ); /*RW*/

/* @brief laserId查找表V71
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V71',                    583 ); /*RW*/

/* @brief laserId查找表V72
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V72',                    584 ); /*RW*/

/* @brief laserId查找表V73
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V73',                    585 ); /*RW*/

/* @brief laserId查找表V74
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V74',                    586 ); /*RW*/

/* @brief laserId查找表V75
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V75',                    587 ); /*RW*/

/* @brief laserId查找表V76
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V76',                    588 ); /*RW*/

/* @brief laserId查找表V77
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V77',                    589 ); /*RW*/

/* @brief laserId查找表V78
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V78',                    590 ); /*RW*/

/* @brief laserId查找表V79
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V79',                    591 ); /*RW*/

/* @brief laserId查找表V80
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V80',                    592 ); /*RW*/

/* @brief laserId查找表V81
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V81',                    593 ); /*RW*/

/* @brief laserId查找表V82
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V82',                    594 ); /*RW*/

/* @brief laserId查找表V83
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V83',                    595 ); /*RW*/

/* @brief laserId查找表V84
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V84',                    596 ); /*RW*/

/* @brief laserId查找表V85
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V85',                    597 ); /*RW*/

/* @brief laserId查找表V86
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V86',                    598 ); /*RW*/

/* @brief laserId查找表V87
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V87',                    599 ); /*RW*/

/* @brief laserId查找表V88
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V88',                    600 ); /*RW*/

/* @brief laserId查找表V89
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V89',                    601 ); /*RW*/

/* @brief laserId查找表V90
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V90',                    602 ); /*RW*/

/* @brief laserId查找表V91
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V91',                    603 ); /*RW*/

/* @brief laserId查找表V92
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V92',                    604 ); /*RW*/

/* @brief laserId查找表V93
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V93',                    605 ); /*RW*/

/* @brief laserId查找表V94
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V94',                    606 ); /*RW*/

/* @brief laserId查找表V95
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V95',                    607 ); /*RW*/

/* @brief laserId查找表V96
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V96',                    608 ); /*RW*/

/* @brief laserId查找表V97
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V97',                    609 ); /*RW*/

/* @brief laserId查找表V98
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V98',                    610 ); /*RW*/

/* @brief laserId查找表V99
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V99',                    611 ); /*RW*/

/* @brief laserId查找表V100
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V100',                   612 ); /*RW*/

/* @brief laserId查找表V101
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V101',                   613 ); /*RW*/

/* @brief laserId查找表V102
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V102',                   614 ); /*RW*/

/* @brief laserId查找表V103
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V103',                   615 ); /*RW*/

/* @brief laserId查找表V104
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V104',                   616 ); /*RW*/

/* @brief laserId查找表V105
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V105',                   617 ); /*RW*/

/* @brief laserId查找表V106
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V106',                   618 ); /*RW*/

/* @brief laserId查找表V107
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V107',                   619 ); /*RW*/

/* @brief laserId查找表V108
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V108',                   620 ); /*RW*/

/* @brief laserId查找表V109
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V109',                   621 ); /*RW*/

/* @brief laserId查找表V110
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V110',                   622 ); /*RW*/

/* @brief laserId查找表V111
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V111',                   623 ); /*RW*/

/* @brief laserId查找表V112
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V112',                   624 ); /*RW*/

/* @brief laserId查找表V113
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V113',                   625 ); /*RW*/

/* @brief laserId查找表V114
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V114',                   626 ); /*RW*/

/* @brief laserId查找表V115
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V115',                   627 ); /*RW*/

/* @brief laserId查找表V116
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V116',                   628 ); /*RW*/

/* @brief laserId查找表V117
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V117',                   629 ); /*RW*/

/* @brief laserId查找表V118
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V118',                   630 ); /*RW*/

/* @brief laserId查找表V119
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V119',                   631 ); /*RW*/

/* @brief laserId查找表V120
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V120',                   632 ); /*RW*/

/* @brief laserId查找表V121
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V121',                   633 ); /*RW*/

/* @brief laserId查找表V122
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V122',                   634 ); /*RW*/

/* @brief laserId查找表V123
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V123',                   635 ); /*RW*/

/* @brief laserId查找表V124
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V124',                   636 ); /*RW*/

/* @brief laserId查找表V125
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V125',                   637 ); /*RW*/

/* @brief laserId查找表V126
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V126',                   638 ); /*RW*/

/* @brief laserId查找表V127
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V127',                   639 ); /*RW*/

/* @brief laserId查找表V128
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V128',                   640 ); /*RW*/

/* @brief laserId查找表V129
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V129',                   641 ); /*RW*/

/* @brief laserId查找表V130
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V130',                   642 ); /*RW*/

/* @brief laserId查找表V131
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V131',                   643 ); /*RW*/

/* @brief laserId查找表V132
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V132',                   644 ); /*RW*/

/* @brief laserId查找表V133
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V133',                   645 ); /*RW*/

/* @brief laserId查找表V134
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V134',                   646 ); /*RW*/

/* @brief laserId查找表V135
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V135',                   647 ); /*RW*/

/* @brief laserId查找表V136
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V136',                   648 ); /*RW*/

/* @brief laserId查找表V137
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V137',                   649 ); /*RW*/

/* @brief laserId查找表V138
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V138',                   650 ); /*RW*/

/* @brief laserId查找表V139
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V139',                   651 ); /*RW*/

/* @brief laserId查找表V140
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V140',                   652 ); /*RW*/

/* @brief laserId查找表V141
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V141',                   653 ); /*RW*/

/* @brief laserId查找表V142
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V142',                   654 ); /*RW*/

/* @brief laserId查找表V143
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V143',                   655 ); /*RW*/

/* @brief laserId查找表V144
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V144',                   656 ); /*RW*/

/* @brief laserId查找表V145
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V145',                   657 ); /*RW*/

/* @brief laserId查找表V146
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V146',                   658 ); /*RW*/

/* @brief laserId查找表V147
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V147',                   659 ); /*RW*/

/* @brief laserId查找表V148
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V148',                   660 ); /*RW*/

/* @brief laserId查找表V149
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V149',                   661 ); /*RW*/

/* @brief laserId查找表V150
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V150',                   662 ); /*RW*/

/* @brief laserId查找表V151
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V151',                   663 ); /*RW*/

/* @brief laserId查找表V152
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V152',                   664 ); /*RW*/

/* @brief laserId查找表V153
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V153',                   665 ); /*RW*/

/* @brief laserId查找表V154
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V154',                   666 ); /*RW*/

/* @brief laserId查找表V155
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V155',                   667 ); /*RW*/

/* @brief laserId查找表V156
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V156',                   668 ); /*RW*/

/* @brief laserId查找表V157
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V157',                   669 ); /*RW*/

/* @brief laserId查找表V158
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V158',                   670 ); /*RW*/

/* @brief laserId查找表V159
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V159',                   671 ); /*RW*/

/* @brief laserId查找表V160
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V160',                   672 ); /*RW*/

/* @brief laserId查找表V161
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V161',                   673 ); /*RW*/

/* @brief laserId查找表V162
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V162',                   674 ); /*RW*/

/* @brief laserId查找表V163
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V163',                   675 ); /*RW*/

/* @brief laserId查找表V164
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V164',                   676 ); /*RW*/

/* @brief laserId查找表V165
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V165',                   677 ); /*RW*/

/* @brief laserId查找表V166
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V166',                   678 ); /*RW*/

/* @brief laserId查找表V167
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V167',                   679 ); /*RW*/

/* @brief laserId查找表V168
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V168',                   680 ); /*RW*/

/* @brief laserId查找表V169
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V169',                   681 ); /*RW*/

/* @brief laserId查找表V170
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V170',                   682 ); /*RW*/

/* @brief laserId查找表V171
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V171',                   683 ); /*RW*/

/* @brief laserId查找表V172
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V172',                   684 ); /*RW*/

/* @brief laserId查找表V173
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V173',                   685 ); /*RW*/

/* @brief laserId查找表V174
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V174',                   686 ); /*RW*/

/* @brief laserId查找表V175
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V175',                   687 ); /*RW*/

/* @brief laserId查找表V176
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V176',                   688 ); /*RW*/

/* @brief laserId查找表V177
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V177',                   689 ); /*RW*/

/* @brief laserId查找表V178
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V178',                   690 ); /*RW*/

/* @brief laserId查找表V179
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V179',                   691 ); /*RW*/

/* @brief laserId查找表V180
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V180',                   692 ); /*RW*/

/* @brief laserId查找表V181
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V181',                   693 ); /*RW*/

/* @brief laserId查找表V182
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V182',                   694 ); /*RW*/

/* @brief laserId查找表V183
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V183',                   695 ); /*RW*/

/* @brief laserId查找表V184
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V184',                   696 ); /*RW*/

/* @brief laserId查找表V185
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V185',                   697 ); /*RW*/

/* @brief laserId查找表V186
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V186',                   698 ); /*RW*/

/* @brief laserId查找表V187
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V187',                   699 ); /*RW*/

/* @brief laserId查找表V188
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V188',                   700 ); /*RW*/

/* @brief laserId查找表V189
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V189',                   701 ); /*RW*/

/* @brief laserId查找表V190
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V190',                   702 ); /*RW*/

/* @brief laserId查找表V191
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V191',                   703 ); /*RW*/

/* @brief laserId查找表V192
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V192',                   704 ); /*RW*/

/* @brief laserId查找表V193
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V193',                   705 ); /*RW*/

/* @brief laserId查找表V194
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V194',                   706 ); /*RW*/

/* @brief laserId查找表V195
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V195',                   707 ); /*RW*/

/* @brief laserId查找表V196
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V196',                   708 ); /*RW*/

/* @brief laserId查找表V197
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V197',                   709 ); /*RW*/

/* @brief laserId查找表V198
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V198',                   710 ); /*RW*/

/* @brief laserId查找表V199
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V199',                   711 ); /*RW*/

/* @brief laserId查找表V200
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V200',                   712 ); /*RW*/

/* @brief laserId查找表V201
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V201',                   713 ); /*RW*/

/* @brief laserId查找表V202
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V202',                   714 ); /*RW*/

/* @brief laserId查找表V203
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V203',                   715 ); /*RW*/

/* @brief laserId查找表V204
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V204',                   716 ); /*RW*/

/* @brief laserId查找表V205
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V205',                   717 ); /*RW*/

/* @brief laserId查找表V206
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V206',                   718 ); /*RW*/

/* @brief laserId查找表V207
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V207',                   719 ); /*RW*/

/* @brief laserId查找表V208
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V208',                   720 ); /*RW*/

/* @brief laserId查找表V209
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V209',                   721 ); /*RW*/

/* @brief laserId查找表V210
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V210',                   722 ); /*RW*/

/* @brief laserId查找表V211
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V211',                   723 ); /*RW*/

/* @brief laserId查找表V212
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V212',                   724 ); /*RW*/

/* @brief laserId查找表V213
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V213',                   725 ); /*RW*/

/* @brief laserId查找表V214
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V214',                   726 ); /*RW*/

/* @brief laserId查找表V215
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V215',                   727 ); /*RW*/

/* @brief laserId查找表V216
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V216',                   728 ); /*RW*/

/* @brief laserId查找表V217
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V217',                   729 ); /*RW*/

/* @brief laserId查找表V218
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V218',                   730 ); /*RW*/

/* @brief laserId查找表V219
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V219',                   731 ); /*RW*/

/* @brief laserId查找表V220
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V220',                   732 ); /*RW*/

/* @brief laserId查找表V221
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V221',                   733 ); /*RW*/

/* @brief laserId查找表V222
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V222',                   734 ); /*RW*/

/* @brief laserId查找表V223
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V223',                   735 ); /*RW*/

/* @brief laserId查找表V224
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V224',                   736 ); /*RW*/

/* @brief laserId查找表V225
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V225',                   737 ); /*RW*/

/* @brief laserId查找表V226
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V226',                   738 ); /*RW*/

/* @brief laserId查找表V227
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V227',                   739 ); /*RW*/

/* @brief laserId查找表V228
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V228',                   740 ); /*RW*/

/* @brief laserId查找表V229
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V229',                   741 ); /*RW*/

/* @brief laserId查找表V230
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V230',                   742 ); /*RW*/

/* @brief laserId查找表V231
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V231',                   743 ); /*RW*/

/* @brief laserId查找表V232
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V232',                   744 ); /*RW*/

/* @brief laserId查找表V233
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V233',                   745 ); /*RW*/

/* @brief laserId查找表V234
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V234',                   746 ); /*RW*/

/* @brief laserId查找表V235
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V235',                   747 ); /*RW*/

/* @brief laserId查找表V236
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V236',                   748 ); /*RW*/

/* @brief laserId查找表V237
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V237',                   749 ); /*RW*/

/* @brief laserId查找表V238
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V238',                   750 ); /*RW*/

/* @brief laserId查找表V239
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V239',                   751 ); /*RW*/

/* @brief laserId查找表V240
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V240',                   752 ); /*RW*/

/* @brief laserId查找表V241
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V241',                   753 ); /*RW*/

/* @brief laserId查找表V242
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V242',                   754 ); /*RW*/

/* @brief laserId查找表V243
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V243',                   755 ); /*RW*/

/* @brief laserId查找表V244
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V244',                   756 ); /*RW*/

/* @brief laserId查找表V245
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V245',                   757 ); /*RW*/

/* @brief laserId查找表V246
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V246',                   758 ); /*RW*/

/* @brief laserId查找表V247
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V247',                   759 ); /*RW*/

/* @brief laserId查找表V248
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V248',                   760 ); /*RW*/

/* @brief laserId查找表V249
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V249',                   761 ); /*RW*/

/* @brief laserId查找表V250
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V250',                   762 ); /*RW*/

/* @brief laserId查找表V251
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V251',                   763 ); /*RW*/

/* @brief laserId查找表V252
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V252',                   764 ); /*RW*/

/* @brief laserId查找表V253
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V253',                   765 ); /*RW*/

/* @brief laserId查找表V254
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V254',                   766 ); /*RW*/

/* @brief laserId查找表V255
 * @param data1(4byte)-  @default [0]
 */
define('REG_LASERID_LUT_V255',                   767 ); /*RW*/



/************通道FOV查找表基地址-最大8个-20240424************/
/* @brief FOV_COS查找表首值，（光学提供，共4个值） 
 *  公式：(int)(cos(a)*32768+0.5)
 * @param data1(4byte)-  @default [0]
 */
define('REG_FOV_COS_LUT_V0',                     3072 ); /*RW*/

/* @brief FOV_SIN查找表首值，（光学提供，共4个值） 
 *  公式：(int)(sin(a)*32768+0.5)
 * @param data1(4byte)-  @default [0]
 */
define('REG_FOV_SIN_LUT_V0',                     3080 ); /*RW*/

/* @brief FOV_COS sqrt查找表首值
 *  公式：(int)(cos(a)/sqrt(2))*32768+0.5)
 * @param data1(4byte)-  @default [0]
 */
define('REG_FOV_COS_SQRT_LUT_V0',                3088 ); /*RW*/

/* @brief FOV_SIN sqrt查找表首值
 *  公式：(int)(sin(a)*sqrt(2)*32768+0.5)
 * @param data1(4byte)-  @default [0]
 */
define('REG_FOV_SIN_SQRT_LUT_V0',                3096 ); /*RW*/

/* @brief FOVX值查找表首值，总长度8
 *  公式：
 * @param data1(4byte)-  @default [0]
 */
define('REG_FOVX_LUT_V0',                        3128 ); /*RW*/

/* @brief FOVY值查找表首值，总长度8
 *  公式：
 * @param data1(4byte)-  @default [0]
 */
define('REG_FOVY_LUT_V0',                        3160 ); /*RW*/

/* @brief FOVZ值查找表首值，总长度8
 *  公式：
 * @param data1(4byte)-  @default [0]
 */
define('REG_FOVZ_LUT_V0',                        3192 ); /*RW*/



/************水平和垂直角度查找表基地址-表尺寸4096************/
/* @brief HCOS值查找表首值，角度范围[9',81']，19200线码盘，填充到长度4096
 *  公式：(int)(cos(a)*32768+0.5)
 * @param data1(4byte)-  @default [0]
 */
define('REG_HCOS_LUT_V0',                        4096 ); /*RW*/

/* @brief HSIN值查找表首值，总长度4096
 *  公式：(int)(sin(a)*32768+0.5)
 * @param data1(4byte)-  @default [0]
 */
define('REG_HSIN_LUT_V0',                        8192 ); /*RW*/

/* @brief VCOS值查找表首值，总长度4096
 *  公式：(int)(cos(a)*32768+0.5-1)
 * @param data1(4byte)-  @default [0]
 */
define('REG_VCOS_LUT_V0',                        12288 ); /*RW*/

/* @brief VSIN值查找表首值，总长度4096
 *  公式：(int)(sin(a)*32768+0.5)
 * @param data1(4byte)-  @default [0]
 */
define('REG_VSIN_LUT_V0',                        16384 ); /*RW*/

/* @brief VERX值查找表首值，总长度4096
 *  公式：
 * @param data1(4byte)-  @default [0]
 */
define('REG_VERX_LUT_V0',                        20480 ); /*RW*/

/* @brief VERY值查找表首值，总长度4096
 *  公式：
 * @param data1(4byte)-  @default [0]
 */
define('REG_VERY_LUT_V0',                        24576 ); /*RW*/

/* @brief VERZ值查找表首值，总长度4096
 *  公式：
 * @param data1(4byte)-  @default [0]
 */
define('REG_VERZ_LUT_V0',                        28672 ); /*RW*/


/* 寄存器总数量 */
define('PCLD_REG_CNT',           28673 );




